<!-- #region Jssor Slider Begin -->
<!-- Generated by Jssor Slider Maker. -->
<!-- This is deep minimized demo, it works alone, it doesn't depend on any javascript library. -->
(function(h,g,c,j,e,l,k){/*! Jssor */
new(function() {});
var f = {
        ec: function(a) {
            return -c.cos(a * c.PI) / 2 + .5
        },
        Jc: function(a) {
            return a
        },
        oe: function(a) {
            return a * a
        },
        pe: function(a) {
            return -a * (a - 2)
        },
        qe: function(a) {
            return (a *= 2) < 1 ? 1 / 2 * a * a : -1 / 2 * (--a * (a - 2) - 1)
        },
        te: function(a) {
            return (a *= 2) < 1 ? 1 / 2 * a * a * a : 1 / 2 * ((a -= 2) * a * a + 2)
        },
        Vd: function(a) {
            return (a *= 2) < 1 ? 1 / 2 * a * a * a * a : -1 / 2 * ((a -= 2) * a * a * a - 2)
        },
        Td: function(a) {
            return 1 - c.cos(c.PI / 2 * a)
        },
        xf: function(a) {
            return a == 0 || a == 1 ? a : (a *= 2) < 1 ? 1 / 2 * c.pow(2, 10 * (a - 1)) : 1 / 2 * (-c.pow(2, -10 * --a) + 2)
        },
        Ce: function(a) {
            return 1 - c.cos(a * c.PI * 2)
        }
    },
    d = {
        De: f.ec,
        l: f.Jc,
        o: f.oe,
        xd: f.qe,
        Af: f.te,
        z: f.Vd,
        rd: f.Td,
        od: f.xf,
        gd: f.Ce
    };
var b = new function() {
    var d = this,
        Ab = /\S+/g,
        F = 1,
        yb = 2,
        fb = 3,
        eb = 4,
        jb = 5,
        G, r = 0,
        i = 0,
        s = 0,
        X = 0,
        z = 0,
        I = navigator,
        ob = I.appName,
        o = I.userAgent,
        p = parseFloat;

    function Ib() {
        if (!G) {
            G = {
                Ae: "ontouchstart" in h || "createTouch" in g
            };
            var a;
            if (I.pointerEnabled || (a = I.msPointerEnabled)) G.Id = a ? "msTouchAction" : "touchAction"
        }
        return G
    }

    function v(j) {
        if (!r) {
            r = -1;
            if (ob == "Microsoft Internet Explorer" && !!h.attachEvent && !!h.ActiveXObject) {
                var e = o.indexOf("MSIE");
                r = F;
                s = p(o.substring(e + 5, o.indexOf(";", e))); /*@cc_on X=@_jscript_version@*/ ;
                i = g.documentMode || s
            } else if (ob == "Netscape" && !!h.addEventListener) {
                var d = o.indexOf("Firefox"),
                    b = o.indexOf("Safari"),
                    f = o.indexOf("Chrome"),
                    c = o.indexOf("AppleWebKit");
                if (d >= 0) {
                    r = yb;
                    i = p(o.substring(d + 8))
                } else if (b >= 0) {
                    var k = o.substring(0, b).lastIndexOf("/");
                    r = f >= 0 ? eb : fb;
                    i = p(o.substring(k + 1, b))
                } else {
                    var a = /Trident\/.*rv:([0-9]{1,}[\.0-9]{0,})/i.exec(o);
                    if (a) {
                        r = F;
                        i = s = p(a[1])
                    }
                }
                if (c >= 0) z = p(o.substring(c + 12))
            } else {
                var a = /(opera)(?:.*version|)[ \/]([\w.]+)/i.exec(o);
                if (a) {
                    r = jb;
                    i = p(a[2])
                }
            }
        }
        return j == r
    }

    function q() {
        return v(F)
    }

    function Q() {
        return q() && (i < 6 || g.compatMode == "BackCompat")
    }

    function db() {
        return v(fb)
    }

    function ib() {
        return v(jb)
    }

    function vb() {
        return db() && z > 534 && z < 535
    }

    function J() {
        v();
        return z > 537 || i > 42 || r == F && i >= 11
    }

    function O() {
        return q() && i < 9
    }

    function wb(a) {
        var b, c;
        return function(f) {
            if (!b) {
                b = e;
                var d = a.substr(0, 1).toUpperCase() + a.substr(1);
                n([a].concat(["WebKit", "ms", "Moz", "O", "webkit"]), function(g, e) {
                    var b = a;
                    if (e) b = g + d;
                    if (f.style[b] != k) return c = b
                })
            }
            return c
        }
    }

    function ub(b) {
        var a;
        return function(c) {
            a = a || wb(b)(c) || b;
            return a
        }
    }
    var K = ub("transform");

    function nb(a) {
        return {}.toString.call(a)
    }
    var kb = {};
    n(["Boolean", "Number", "String", "Function", "Array", "Date", "RegExp", "Object"], function(a) {
        kb["[object " + a + "]"] = a.toLowerCase()
    });

    function n(b, d) {
        var a, c;
        if (nb(b) == "[object Array]") {
            for (a = 0; a < b.length; a++)
                if (c = d(b[a], a, b)) return c
        } else
            for (a in b)
                if (c = d(b[a], a, b)) return c
    }

    function C(a) {
        return a == j ? String(a) : kb[nb(a)] || "object"
    }

    function lb(a) {
        for (var b in a) return e
    }

    function A(a) {
        try {
            return C(a) == "object" && !a.nodeType && a != a.window && (!a.constructor || {}.hasOwnProperty.call(a.constructor.prototype, "isPrototypeOf"))
        } catch (b) {}
    }

    function u(a, b) {
        return {
            x: a,
            y: b
        }
    }

    function rb(b, a) {
        setTimeout(b, a || 0)
    }

    function H(b, d, c) {
        var a = !b || b == "inherit" ? "" : b;
        n(d, function(c) {
            var b = c.exec(a);
            if (b) {
                var d = a.substr(0, b.index),
                    e = a.substr(b.index + b[0].length + 1, a.length - 1);
                a = d + e
            }
        });
        a = c + (!a.indexOf(" ") ? "" : " ") + a;
        return a
    }

    function tb(b, a) {
        if (i < 9) b.style.filter = a
    }
    d.Ne = Ib;
    d.Ed = q;
    d.Me = db;
    d.Vc = ib;
    d.Le = J;
    d.tb = O;
    wb("transform");
    d.zd = function() {
        return i
    };
    d.Je = function() {
        v();
        return z
    };
    d.U = rb;

    function Y(a) {
        a.constructor === Y.caller && a.Wc && a.Wc.apply(a, Y.caller.arguments)
    }
    d.Wc = Y;
    d.Jb = function(a) {
        if (d.He(a)) a = g.getElementById(a);
        return a
    };

    function t(a) {
        return a || h.event
    }
    d.Xc = t;
    d.zc = function(b) {
        b = t(b);
        var a = b.target || b.srcElement || g;
        if (a.nodeType == 3) a = d.Sc(a);
        return a
    };
    d.Nc = function(a) {
        a = t(a);
        return {
            x: a.pageX || a.clientX || 0,
            y: a.pageY || a.clientY || 0
        }
    };

    function D(c, d, a) {
        if (a !== k) c.style[d] = a == k ? "" : a;
        else {
            var b = c.currentStyle || c.style;
            a = b[d];
            if (a == "" && h.getComputedStyle) {
                b = c.ownerDocument.defaultView.getComputedStyle(c, j);
                b && (a = b.getPropertyValue(d) || b[d])
            }
            return a
        }
    }

    function ab(b, c, a, d) {
        if (a !== k) {
            if (a == j) a = "";
            else d && (a += "px");
            D(b, c, a)
        } else return p(D(b, c))
    }

    function m(c, a) {
        var d = a ? ab : D,
            b;
        if (a & 4) b = ub(c);
        return function(e, f) {
            return d(e, b ? b(e) : c, f, a & 2)
        }
    }

    function Db(b) {
        if (q() && s < 9) {
            var a = /opacity=([^)]*)/.exec(b.style.filter || "");
            return a ? p(a[1]) / 100 : 1
        } else return p(b.style.opacity || "1")
    }

    function Fb(b, a, f) {
        if (q() && s < 9) {
            var h = b.style.filter || "",
                i = new RegExp(/[\s]*alpha\([^\)]*\)/g),
                e = c.round(100 * a),
                d = "";
            if (e < 100 || f) d = "alpha(opacity=" + e + ") ";
            var g = H(h, [i], d);
            tb(b, g)
        } else b.style.opacity = a == 1 ? "" : c.round(a * 100) / 100
    }
    var L = {
        f: ["rotate"],
        gb: ["rotateX"],
        fb: ["rotateY"],
        Wb: ["skewX"],
        Vb: ["skewY"]
    };
    if (!J()) L = B(L, {
        C: ["scaleX", 2],
        D: ["scaleY", 2],
        db: ["translateZ", 1]
    });

    function M(d, a) {
        var c = "";
        if (a) {
            if (q() && i && i < 10) {
                delete a.gb;
                delete a.fb;
                delete a.db
            }
            b.m(a, function(d, b) {
                var a = L[b];
                if (a) {
                    var e = a[1] || 0;
                    if (N[b] != d) c += " " + a[0] + "(" + d + (["deg", "px", ""])[e] + ")"
                }
            });
            if (J()) {
                if (a.wb || a.pb || a.db) c += " translate3d(" + (a.wb || 0) + "px," + (a.pb || 0) + "px," + (a.db || 0) + "px)";
                if (a.C == k) a.C = 1;
                if (a.D == k) a.D = 1;
                if (a.C != 1 || a.D != 1) c += " scale3d(" + a.C + ", " + a.D + ", 1)"
            }
        }
        d.style[K(d)] = c
    }
    d.Uc = m("transformOrigin", 4);
    d.Be = m("backfaceVisibility", 4);
    d.Ye = m("transformStyle", 4);
    d.hf = m("perspective", 6);
    d.lf = m("perspectiveOrigin", 4);
    d.kf = function(a, b) {
        if (q() && s < 9 || s < 10 && Q()) a.style.zoom = b == 1 ? "" : b;
        else {
            var c = K(a),
                f = "scale(" + b + ")",
                e = a.style[c],
                g = new RegExp(/[\s]*scale\(.*?\)/g),
                d = H(e, [g], f);
            a.style[c] = d
        }
    };
    d.Dc = function(b, a) {
        return function(c) {
            c = t(c);
            var f = c.type,
                e = c.relatedTarget || (f == "mouseout" ? c.toElement : c.fromElement);
            (!e || e !== a && !d.Cf(a, e)) && b(c)
        }
    };
    d.j = function(a, e, b, c) {
        a = d.Jb(a);
        if (a.addEventListener) {
            e == "mousewheel" && a.addEventListener("DOMMouseScroll", b, c);
            a.addEventListener(e, b, c)
        } else if (a.attachEvent) {
            a.attachEvent("on" + e, b);
            c && a.setCapture && a.setCapture()
        }
    };
    d.V = function(a, c, e, b) {
        a = d.Jb(a);
        if (a.removeEventListener) {
            c == "mousewheel" && a.removeEventListener("DOMMouseScroll", e, b);
            a.removeEventListener(c, e, b)
        } else if (a.detachEvent) {
            a.detachEvent("on" + c, e);
            b && a.releaseCapture && a.releaseCapture()
        }
    };
    d.Pb = function(a) {
        a = t(a);
        a.preventDefault && a.preventDefault();
        a.cancel = e;
        a.returnValue = l
    };
    d.Ef = function(a) {
        a = t(a);
        a.stopPropagation && a.stopPropagation();
        a.cancelBubble = e
    };
    d.T = function(d, c) {
        var a = [].slice.call(arguments, 2),
            b = function() {
                var b = a.concat([].slice.call(arguments, 0));
                return c.apply(d, b)
            };
        return b
    };
    d.Qc = function(a, b) {
        if (b == k) return a.textContent || a.innerText;
        var c = g.createTextNode(b);
        d.Ac(a);
        a.appendChild(c)
    };
    d.Qb = function(d, c) {
        for (var b = [], a = d.firstChild; a; a = a.nextSibling)(c || a.nodeType == 1) && b.push(a);
        return b
    };

    function mb(a, c, e, b) {
        b = b || "u";
        for (a = a ? a.firstChild : j; a; a = a.nextSibling)
            if (a.nodeType == 1) {
                if (U(a, b) == c) return a;
                if (!e) {
                    var d = mb(a, c, e, b);
                    if (d) return d
                }
            }
    }
    d.I = mb;

    function S(a, d, f, b) {
        b = b || "u";
        var c = [];
        for (a = a ? a.firstChild : j; a; a = a.nextSibling)
            if (a.nodeType == 1) {
                U(a, b) == d && c.push(a);
                if (!f) {
                    var e = S(a, d, f, b);
                    if (e.length) c = c.concat(e)
                }
            }
        return c
    }
    d.Hf = S;

    function gb(a, c, d) {
        for (a = a ? a.firstChild : j; a; a = a.nextSibling)
            if (a.nodeType == 1) {
                if (a.tagName == c) return a;
                if (!d) {
                    var b = gb(a, c, d);
                    if (b) return b
                }
            }
    }
    d.If = gb;

    function xb(a, c, e) {
        var b = [];
        for (a = a ? a.firstChild : j; a; a = a.nextSibling)
            if (a.nodeType == 1) {
                (!c || a.tagName == c) && b.push(a);
                if (!e) {
                    var d = xb(a, c, e);
                    if (d.length) b = b.concat(d)
                }
            }
        return b
    }
    d.Lf = xb;
    d.Kf = function(b, a) {
        return b.getElementsByTagName(a)
    };

    function B() {
        var e = arguments,
            d, c, b, a, g = 1 & e[0],
            f = 1 + g;
        d = e[f - 1] || {};
        for (; f < e.length; f++)
            if (c = e[f])
                for (b in c) {
                    a = c[b];
                    if (a !== k) {
                        a = c[b];
                        var h = d[b];
                        d[b] = g && (A(h) || A(a)) ? B(g, {}, h, a) : a
                    }
                }
            return d
    }
    d.N = B;

    function Z(f, g) {
        var d = {},
            c, a, b;
        for (c in f) {
            a = f[c];
            b = g[c];
            if (a !== b) {
                var e;
                if (A(a) && A(b)) {
                    a = Z(a, b);
                    e = !lb(a)
                }!e && (d[c] = a)
            }
        }
        return d
    }
    d.Pc = function(a) {
        return C(a) == "function"
    };
    d.He = function(a) {
        return C(a) == "string"
    };
    d.Rc = function(a) {
        return !isNaN(p(a)) && isFinite(a)
    };
    d.m = n;
    d.ze = A;

    function R(a) {
        return g.createElement(a)
    }
    d.Ib = function() {
        return R("DIV")
    };
    d.mf = function() {
        return R("SPAN")
    };
    d.Ad = function() {};

    function V(b, c, a) {
        if (a == k) return b.getAttribute(c);
        b.setAttribute(c, a)
    }

    function U(a, b) {
        return V(a, b) || V(a, "data-" + b)
    }
    d.L = V;
    d.s = U;

    function x(b, a) {
        if (a == k) return b.className;
        b.className = a
    }
    d.Kc = x;

    function qb(b) {
        var a = {};
        n(b, function(b) {
            a[b] = b
        });
        return a
    }

    function sb(b, a) {
        return b.match(a || Ab)
    }

    function P(b, a) {
        return qb(sb(b || "", a))
    }
    d.pf = sb;

    function bb(b, c) {
        var a = "";
        n(c, function(c) {
            a && (a += b);
            a += c
        });
        return a
    }

    function E(a, c, b) {
        x(a, bb(" ", B(Z(P(x(a)), P(c)), P(b))))
    }
    d.Sc = function(a) {
        return a.parentNode
    };
    d.W = function(a) {
        d.ab(a, "none")
    };
    d.J = function(a, b) {
        d.ab(a, b ? "none" : "")
    };
    d.sf = function(b, a) {
        b.removeAttribute(a)
    };
    d.uf = function() {
        return q() && i < 10
    };
    d.vf = function(d, a) {
        if (a) d.style.clip = "rect(" + c.round(a.g || a.K || 0) + "px " + c.round(a.E) + "px " + c.round(a.F) + "px " + c.round(a.c || a.G || 0) + "px)";
        else if (a !== k) {
            var g = d.style.cssText,
                f = [new RegExp(/[\s]*clip: rect\(.*?\)[;]?/i), new RegExp(/[\s]*cliptop: .*?[;]?/i), new RegExp(/[\s]*clipright: .*?[;]?/i), new RegExp(/[\s]*clipbottom: .*?[;]?/i), new RegExp(/[\s]*clipleft: .*?[;]?/i)],
                e = H(g, f, "");
            b.Bb(d, e)
        }
    };
    d.mb = function() {
        return +new Date
    };
    d.O = function(b, a) {
        b.appendChild(a)
    };
    d.Xb = function(b, a, c) {
        (c || a.parentNode).insertBefore(b, a)
    };
    d.Rb = function(b, a) {
        a = a || b.parentNode;
        a && a.removeChild(b)
    };
    d.Ud = function(a, b) {
        n(a, function(a) {
            d.Rb(a, b)
        })
    };
    d.Ac = function(a) {
        d.Ud(d.Qb(a, e), a)
    };
    d.Yd = function(a, b) {
        var c = d.Sc(a);
        b & 1 && d.Y(a, (d.v(c) - d.v(a)) / 2);
        b & 2 && d.Z(a, (d.A(c) - d.A(a)) / 2)
    };
    d.me = function(b, a) {
        return parseInt(b, a || 10)
    };
    d.ce = p;
    d.Cf = function(b, a) {
        var c = g.body;
        while (a && b !== a && c !== a) try {
            a = a.parentNode
        } catch (d) {
            return l
        }
        return b === a
    };

    function W(e, c, b) {
        var a = e.cloneNode(!c);
        !b && d.sf(a, "id");
        return a
    }
    d.eb = W;
    d.Mb = function(f, g) {
        var a = new Image;

        function b(f, e) {
            d.V(a, "load", b);
            d.V(a, "abort", c);
            d.V(a, "error", c);
            g && g(a, e)
        }

        function c(a) {
            b(a, e)
        }
        if (ib() && i < 11.6 || !f) b(!f);
        else {
            d.j(a, "load", b);
            d.j(a, "abort", c);
            d.j(a, "error", c);
            a.src = f
        }
    };
    d.we = function(e, a, f) {
        var c = e.length + 1;

        function b(b) {
            c--;
            if (a && b && b.src == a.src) a = b;
            !c && f && f(a)
        }
        n(e, function(a) {
            d.Mb(a.src, b)
        });
        b()
    };
    d.ve = function(a, g, i, h) {
        if (h) a = W(a);
        var c = S(a, g);
        if (!c.length) c = b.Kf(a, g);
        for (var f = c.length - 1; f > -1; f--) {
            var d = c[f],
                e = W(i);
            x(e, x(d));
            b.Bb(e, d.style.cssText);
            b.Xb(e, d);
            b.Rb(d)
        }
        return a
    };

    function Gb(a) {
        var l = this,
            p = "",
            r = ["av", "pv", "ds", "dn"],
            f = [],
            q, j = 0,
            h = 0,
            e = 0;

        function i() {
            E(a, q, f[e || j || h & 2 || h]);
            b.jb(a, "pointer-events", e ? "none" : "")
        }

        function c() {
            j = 0;
            i();
            d.V(g, "mouseup", c);
            d.V(g, "touchend", c);
            d.V(g, "touchcancel", c)
        }

        function o(a) {
            if (e) d.Pb(a);
            else {
                j = 4;
                i();
                d.j(g, "mouseup", c);
                d.j(g, "touchend", c);
                d.j(g, "touchcancel", c)
            }
        }
        l.ue = function(a) {
            if (a === k) return h;
            h = a & 2 || a & 1;
            i()
        };
        l.Ic = function(a) {
            if (a === k) return !e;
            e = a ? 0 : 3;
            i()
        };
        l.kb = a = d.Jb(a);
        var m = b.pf(x(a));
        if (m) p = m.shift();
        n(r, function(a) {
            f.push(p + a)
        });
        q = bb(" ", f);
        f.unshift("");
        d.j(a, "mousedown", o);
        d.j(a, "touchstart", o)
    }
    d.xc = function(a) {
        return new Gb(a)
    };
    d.jb = D;
    d.Hb = m("overflow");
    d.Z = m("top", 2);
    d.Y = m("left", 2);
    d.v = m("width", 2);
    d.A = m("height", 2);
    d.se = m("marginLeft", 2);
    d.re = m("marginTop", 2);
    d.H = m("position");
    d.ab = m("display");
    d.Q = m("zIndex", 1);
    d.Fb = function(b, a, c) {
        if (a != k) Fb(b, a, c);
        else return Db(b)
    };
    d.Bb = function(a, b) {
        if (b != k) a.style.cssText = b;
        else return a.style.cssText
    };
    var T = {
        a: d.Fb,
        g: d.Z,
        c: d.Y,
        cb: d.v,
        bb: d.A,
        Eb: d.H,
        Sf: d.ab,
        u: d.Q
    };

    function w(g, l) {
        var f = O(),
            b = J(),
            e = vb(),
            h = K(g);

        function i(b, d, a) {
            var e = b.vb(u(-d / 2, -a / 2)),
                f = b.vb(u(d / 2, -a / 2)),
                g = b.vb(u(d / 2, a / 2)),
                h = b.vb(u(-d / 2, a / 2));
            b.vb(u(300, 300));
            return u(c.min(e.x, f.x, g.x, h.x) + d / 2, c.min(e.y, f.y, g.y, h.y) + a / 2)
        }

        function a(e, a) {
            a = a || {};
            var g = a.db || 0,
                l = (a.gb || 0) % 360,
                m = (a.fb || 0) % 360,
                o = (a.f || 0) % 360,
                p = a.Tf;
            if (f) {
                g = 0;
                l = 0;
                m = 0;
                p = 0
            }
            var c = new Cb(a.wb, a.pb, g);
            c.gb(l);
            c.fb(m);
            c.ne(o);
            c.be(a.Wb, a.Vb);
            c.fc(a.C, a.D, p);
            if (b) {
                c.ub(a.G, a.K);
                e.style[h] = c.le()
            } else if (!X || X < 9) {
                var j = "";
                if (o || a.C != k && a.C != 1 || a.D != k && a.D != 1) {
                    var n = i(c, a.ob, a.sb);
                    d.re(e, n.y);
                    d.se(e, n.x);
                    j = c.ke()
                }
                var r = e.style.filter,
                    s = new RegExp(/[\s]*progid:DXImageTransform\.Microsoft\.Matrix\([^\)]*\)/g),
                    q = H(r, [s], j);
                tb(e, q)
            }
        }
        w = function(f, c) {
            c = c || {};
            var h = c.G,
                i = c.K,
                g;
            n(T, function(a, b) {
                g = c[b];
                g !== k && a(f, g)
            });
            d.vf(f, c.k);
            if (!b) {
                h != k && d.Y(f, (c.Cd || 0) + h);
                i != k && d.Z(f, (c.Dd || 0) + i)
            }
            if (c.je)
                if (e) rb(d.T(j, M, f, c));
                else a(f, c)
        };
        d.Ab = M;
        if (e) d.Ab = w;
        if (f) d.Ab = a;
        else if (!b) a = M;
        d.P = w;
        w(g, l)
    }
    d.Ab = w;
    d.P = w;

    function Cb(i, l, p) {
        var d = this,
            b = [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, i || 0, l || 0, p || 0, 1],
            h = c.sin,
            g = c.cos,
            m = c.tan;

        function f(a) {
            return a * c.PI / 180
        }

        function o(a, b) {
            return {
                x: a,
                y: b
            }
        }

        function n(c, e, l, m, o, r, t, u, w, z, A, C, E, b, f, k, a, g, i, n, p, q, s, v, x, y, B, D, F, d, h, j) {
            return [c * a + e * p + l * x + m * F, c * g + e * q + l * y + m * d, c * i + e * s + l * B + m * h, c * n + e * v + l * D + m * j, o * a + r * p + t * x + u * F, o * g + r * q + t * y + u * d, o * i + r * s + t * B + u * h, o * n + r * v + t * D + u * j, w * a + z * p + A * x + C * F, w * g + z * q + A * y + C * d, w * i + z * s + A * B + C * h, w * n + z * v + A * D + C * j, E * a + b * p + f * x + k * F, E * g + b * q + f * y + k * d, E * i + b * s + f * B + k * h, E * n + b * v + f * D + k * j]
        }

        function e(c, a) {
            return n.apply(j, (a || b).concat(c))
        }
        d.fc = function(a, c, d) {
            if (a == k) a = 1;
            if (c == k) c = 1;
            if (d == k) d = 1;
            if (a != 1 || c != 1 || d != 1) b = e([a, 0, 0, 0, 0, c, 0, 0, 0, 0, d, 0, 0, 0, 0, 1])
        };
        d.ub = function(a, c, d) {
            b[12] += a || 0;
            b[13] += c || 0;
            b[14] += d || 0
        };
        d.gb = function(c) {
            if (c) {
                a = f(c);
                var d = g(a),
                    i = h(a);
                b = e([1, 0, 0, 0, 0, d, i, 0, 0, -i, d, 0, 0, 0, 0, 1])
            }
        };
        d.fb = function(c) {
            if (c) {
                a = f(c);
                var d = g(a),
                    i = h(a);
                b = e([d, 0, -i, 0, 0, 1, 0, 0, i, 0, d, 0, 0, 0, 0, 1])
            }
        };
        d.ne = function(c) {
            if (c) {
                a = f(c);
                var d = g(a),
                    i = h(a);
                b = e([d, i, 0, 0, -i, d, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1])
            }
        };
        d.be = function(a, c) {
            if (a || c) {
                i = f(a);
                l = f(c);
                b = e([1, m(l), 0, 0, m(i), 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1])
            }
        };
        d.vb = function(c) {
            var a = e(b, [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, c.x, c.y, 0, 1]);
            return o(a[12], a[13])
        };
        d.le = function() {
            return "matrix3d(" + b.join(",") + ")"
        };
        d.ke = function() {
            return "progid:DXImageTransform.Microsoft.Matrix(M11=" + b[0] + ", M12=" + b[4] + ", M21=" + b[1] + ", M22=" + b[5] + ", SizingMethod='auto expand')"
        }
    }
    new function() {
        var a = this;

        function b(d, g) {
            for (var j = d[0].length, i = d.length, h = g[0].length, f = [], c = 0; c < i; c++)
                for (var k = f[c] = [], b = 0; b < h; b++) {
                    for (var e = 0, a = 0; a < j; a++) e += d[c][a] * g[a][b];
                    k[b] = e
                }
            return f
        }
        a.C = function(b, c) {
            return a.Fd(b, c, 0)
        };
        a.D = function(b, c) {
            return a.Fd(b, 0, c)
        };
        a.Fd = function(a, c, d) {
            return b(a, [
                [c, 0],
                [0, d]
            ])
        };
        a.vb = function(d, c) {
            var a = b(d, [
                [c.x],
                [c.y]
            ]);
            return u(a[0][0], a[1][0])
        }
    };
    var N = {
        Cd: 0,
        Dd: 0,
        G: 0,
        K: 0,
        n: 1,
        C: 1,
        D: 1,
        f: 0,
        gb: 0,
        fb: 0,
        wb: 0,
        pb: 0,
        db: 0,
        Wb: 0,
        Vb: 0
    };
    d.Jd = function(a) {
        var c = a || {};
        if (a)
            if (b.Pc(a)) c = {
                mc: c
            };
            else if (b.Pc(a.k)) c.k = {
            mc: a.k
        };
        return c
    };
    d.Kd = function(l, m, x, q, z, A, n) {
        var a = m;
        if (l) {
            a = {};
            for (var g in m) {
                var B = A[g] || 1,
                    w = z[g] || [0, 1],
                    d = (x - w[0]) / w[1];
                d = c.min(c.max(d, 0), 1);
                d = d * B;
                var u = c.floor(d);
                if (d != u) d -= u;
                var h = q.mc || f.ec,
                    i, C = l[g],
                    o = m[g];
                if (b.Rc(o)) {
                    h = q[g] || h;
                    var y = h(d);
                    i = C + o * y
                } else {
                    i = b.N({
                        Sb: {}
                    }, l[g]);
                    var v = q[g] || {};
                    b.m(o.Sb || o, function(e, a) {
                        h = v[a] || v.mc || h;
                        var c = h(d),
                            b = e * c;
                        i.Sb[a] = b;
                        i[a] += b
                    })
                }
                a[g] = i
            }
            var t = b.m(m, function(b, a) {
                return N[a] != k
            });
            t && b.m(N, function(c, b) {
                if (a[b] == k && l[b] !== k) a[b] = l[b]
            });
            if (t) {
                if (a.n) a.C = a.D = a.n;
                a.ob = n.ob;
                a.sb = n.sb;
                a.je = e
            }
        }
        if (m.k && n.ub) {
            var p = a.k.Sb,
                s = (p.g || 0) + (p.F || 0),
                r = (p.c || 0) + (p.E || 0);
            a.c = (a.c || 0) + r;
            a.g = (a.g || 0) + s;
            a.k.c -= r;
            a.k.E -= r;
            a.k.g -= s;
            a.k.F -= s
        }
        if (a.k && b.uf() && !a.k.g && !a.k.c && !a.k.K && !a.k.G && a.k.E == n.ob && a.k.F == n.sb) a.k = j;
        return a
    }
};

function n() {
    var a = this,
        d = [];

    function i(a, b) {
        d.push({
            nc: a,
            uc: b
        })
    }

    function g(a, c) {
        b.m(d, function(b, e) {
            b.nc == a && b.uc === c && d.splice(e, 1)
        })
    }
    a.Gb = a.addEventListener = i;
    a.removeEventListener = g;
    a.r = function(a) {
        var c = [].slice.call(arguments, 1);
        b.m(d, function(b) {
            b.nc == a && b.uc.apply(h, c)
        })
    }
}
var m = function(z, C, i, J, M, L) {
    z = z || 0;
    var a = this,
        q, n, o, u, A = 0,
        G, H, F, B, y = 0,
        g = 0,
        m = 0,
        D, k, f, d, p, w = [],
        x;

    function O(a) {
        f += a;
        d += a;
        k += a;
        g += a;
        m += a;
        y += a
    }

    function t(o) {
        var h = o;
        if (p && (h >= d || h <= f)) h = ((h - f) % p + p) % p + f;
        if (!D || u || g != h) {
            var j = c.min(h, d);
            j = c.max(j, f);
            if (!D || u || j != m) {
                if (L) {
                    var l = (j - k) / (C || 1);
                    if (i.Rd) l = 1 - l;
                    var n = b.Kd(M, L, l, G, F, H, i);
                    if (x) b.m(n, function(b, a) {
                        x[a] && x[a](J, b)
                    });
                    else b.P(J, n)
                }
                a.Ec(m - k, j - k);
                m = j;
                b.m(w, function(b, c) {
                    var a = o < g ? w[w.length - c - 1] : b;
                    a.lb(m - y)
                });
                var r = g,
                    q = m;
                g = h;
                D = e;
                a.Ob(r, q)
            }
        }
    }

    function E(a, b, e) {
        b && a.M(d);
        if (!e) {
            f = c.min(f, a.bd() + y);
            d = c.max(d, a.Cc() + y)
        }
        w.push(a)
    }
    var r = h.requestAnimationFrame || h.webkitRequestAnimationFrame || h.mozRequestAnimationFrame || h.msRequestAnimationFrame;
    if (b.Me() && b.zd() < 7) r = j;
    r = r || function(a) {
        b.U(a, i.hb)
    };

    function I() {
        if (q) {
            var d = b.mb(),
                e = c.min(d - A, i.ed),
                a = g + e * o;
            A = d;
            if (a * o >= n * o) a = n;
            t(a);
            if (!u && a * o >= n * o) K(B);
            else r(I)
        }
    }

    function s(h, i, j) {
        if (!q) {
            q = e;
            u = j;
            B = i;
            h = c.max(h, f);
            h = c.min(h, d);
            n = h;
            o = n < g ? -1 : 1;
            a.id();
            A = b.mb();
            r(I)
        }
    }

    function K(b) {
        if (q) {
            u = q = B = l;
            a.jd();
            b && b()
        }
    }
    a.kd = function(a, b, c) {
        s(a ? g + a : d, b, c)
    };
    a.ld = s;
    a.qb = K;
    a.ge = function(a) {
        s(a)
    };
    a.ib = function() {
        return g
    };
    a.nd = function() {
        return n
    };
    a.Nb = function() {
        return m
    };
    a.lb = t;
    a.ub = function(a) {
        t(g + a)
    };
    a.pd = function() {
        return q
    };
    a.fe = function(a) {
        p = a
    };
    a.M = O;
    a.qd = function(a, b) {
        E(a, 0, b)
    };
    a.rc = function(a) {
        E(a, 1)
    };
    a.bd = function() {
        return f
    };
    a.Cc = function() {
        return d
    };
    a.Ob = a.id = a.jd = a.Ec = b.Ad;
    a.qc = b.mb();
    i = b.N({
        hb: 16,
        ed: 50
    }, i);
    p = i.sd;
    x = i.de;
    f = k = z;
    d = z + C;
    H = i.S || {};
    F = i.nb || {};
    G = b.Jd(i.e)
};
var o = new function() {
        var h = this,
            t = 1,
            q = 2,
            r = 4,
            s = 8,
            w = 256,
            x = 512,
            v = 1024,
            u = 2048,
            j = u + t,
            i = u + q,
            o = x + t,
            m = x + q,
            n = w + r,
            k = w + s,
            l = v + r;

        function g(b, a, c) {
            c.push(a);
            b[a] = b[a] || [];
            b[a].push(c)
        }
        h.dc = function(f) {
            for (var d = f.q, e = f.B, s = f.tc, t = f.he, r = [], a = 0, b = 0, p = d - 1, q = e - 1, h = t - 1, c, b = 0; b < e; b++)
                for (a = 0; a < d; a++) {
                    switch (s) {
                        case j:
                            c = h - (a * e + (q - b));
                            break;
                        case l:
                            c = h - (b * d + (p - a));
                            break;
                        case o:
                            c = h - (a * e + b);
                        case n:
                            c = h - (b * d + a);
                            break;
                        case i:
                            c = a * e + b;
                            break;
                        case k:
                            c = b * d + (p - a);
                            break;
                        case m:
                            c = a * e + (q - b);
                            break;
                        default:
                            c = b * d + a
                    }
                    g(r, c, [b, a])
                }
            return r
        };
        h.ie = function(d) {
            for (var e = [], a, b = 0; b < d.B; b++)
                for (a = 0; a < d.q; a++) g(e, c.ceil(1e5 * c.random()) % 13, [b, a]);
            return e
        }
    },
    s = function(k, s, q, u, z) {
        var d = this,
            v, g, a, y = 0,
            x = u.xe,
            r, h = 8;

        function t(a) {
            if (a.g) a.K = a.g;
            if (a.c) a.G = a.c;
            b.m(a, function(a) {
                b.ze(a) && t(a)
            })
        }

        function i(g, d) {
            var a = {
                hb: d,
                i: 1,
                U: 0,
                q: 1,
                B: 1,
                a: 0,
                n: 0,
                k: 0,
                ub: l,
                bc: l,
                Rd: l,
                Db: o.ie,
                tc: 1032,
                R: {
                    Ub: 0,
                    Cb: 0
                },
                e: f.ec,
                S: {},
                ac: [],
                nb: {}
            };
            b.N(a, g);
            t(a);
            a.he = a.q * a.B;
            a.e = b.Jd(a.e);
            a.Xd = c.ceil(a.i / a.hb);
            a.Zd = function(c, b) {
                c /= a.q;
                b /= a.B;
                var f = c + "x" + b;
                if (!a.ac[f]) {
                    a.ac[f] = {
                        cb: c,
                        bb: b
                    };
                    for (var d = 0; d < a.q; d++)
                        for (var e = 0; e < a.B; e++) a.ac[f][e + "," + d] = {
                            g: e * b,
                            E: d * c + c,
                            F: e * b + b,
                            c: d * c
                        }
                }
                return a.ac[f]
            };
            if (a.p) {
                a.p = i(a.p, d);
                a.bc = e
            }
            return a
        }

        function p(B, h, a, w, o, m) {
            var z = this,
                u, v = {},
                i = {},
                n = [],
                f, d, s, q = a.R.Ub || 0,
                r = a.R.Cb || 0,
                g = a.Zd(o, m),
                p = C(a),
                D = p.length - 1,
                t = a.i + a.U * D,
                x = w + t,
                k = a.bc,
                y;
            x += 50;

            function C(a) {
                var b = a.Db(a);
                return a.Rd ? b.reverse() : b
            }
            z.Nd = x;
            z.Yb = function(d) {
                d -= w;
                var e = d < t;
                if (e || y) {
                    y = e;
                    if (!k) d = t - d;
                    var f = c.ceil(d / a.hb);
                    b.m(i, function(a, e) {
                        var d = c.max(f, a.yf);
                        d = c.min(d, a.length - 1);
                        if (a.Tc != d) {
                            if (!a.Tc && !k) b.J(n[e]);
                            else d == a.rf && k && b.W(n[e]);
                            a.Tc = d;
                            b.P(n[e], a[d])
                        }
                    })
                }
            };
            h = b.eb(h);
            b.Ab(h, j);
            if (b.tb()) {
                var E = !h["no-image"],
                    A = b.Lf(h);
                b.m(A, function(a) {
                    (E || a["jssor-slider"]) && b.Fb(a, b.Fb(a), e)
                })
            }
            b.m(p, function(h, j) {
                b.m(h, function(G) {
                    var K = G[0],
                        J = G[1],
                        t = K + "," + J,
                        n = l,
                        p = l,
                        x = l;
                    if (q && J % 2) {
                        if (q & 3) n = !n;
                        if (q & 12) p = !p;
                        if (q & 16) x = !x
                    }
                    if (r && K % 2) {
                        if (r & 3) n = !n;
                        if (r & 12) p = !p;
                        if (r & 16) x = !x
                    }
                    a.g = a.g || a.k & 4;
                    a.F = a.F || a.k & 8;
                    a.c = a.c || a.k & 1;
                    a.E = a.E || a.k & 2;
                    var E = p ? a.F : a.g,
                        B = p ? a.g : a.F,
                        D = n ? a.E : a.c,
                        C = n ? a.c : a.E;
                    a.k = E || B || D || C;
                    s = {};
                    d = {
                        K: 0,
                        G: 0,
                        a: 1,
                        cb: o,
                        bb: m
                    };
                    f = b.N({}, d);
                    u = b.N({}, g[t]);
                    if (a.a) d.a = 2 - a.a;
                    if (a.u) {
                        d.u = a.u;
                        f.u = 0
                    }
                    var I = a.q * a.B > 1 || a.k;
                    if (a.n || a.f) {
                        var H = e;
                        if (b.tb())
                            if (a.q * a.B > 1) H = l;
                            else I = l;
                        if (H) {
                            d.n = a.n ? a.n - 1 : 1;
                            f.n = 1;
                            if (b.tb() || b.Vc()) d.n = c.min(d.n, 2);
                            var N = a.f || 0;
                            d.f = N * 360 * (x ? -1 : 1);
                            f.f = 0
                        }
                    }
                    if (I) {
                        var h = u.Sb = {};
                        if (a.k) {
                            var w = a.Pf || 1;
                            if (E && B) {
                                h.g = g.bb / 2 * w;
                                h.F = -h.g
                            } else if (E) h.F = -g.bb * w;
                            else if (B) h.g = g.bb * w;
                            if (D && C) {
                                h.c = g.cb / 2 * w;
                                h.E = -h.c
                            } else if (D) h.E = -g.cb * w;
                            else if (C) h.c = g.cb * w
                        }
                        s.k = u;
                        f.k = g[t]
                    }
                    var L = n ? 1 : -1,
                        M = p ? 1 : -1;
                    if (a.x) d.G += o * a.x * L;
                    if (a.y) d.K += m * a.y * M;
                    b.m(d, function(a, c) {
                        if (b.Rc(a))
                            if (a != f[c]) s[c] = a - f[c]
                    });
                    v[t] = k ? f : d;
                    var F = a.Xd,
                        A = c.round(j * a.U / a.hb);
                    i[t] = new Array(A);
                    i[t].yf = A;
                    i[t].rf = A + F - 1;
                    for (var z = 0; z <= F; z++) {
                        var y = b.Kd(f, s, z / F, a.e, a.nb, a.S, {
                            ub: a.ub,
                            ob: o,
                            sb: m
                        });
                        y.u = y.u || 1;
                        i[t].push(y)
                    }
                })
            });
            p.reverse();
            b.m(p, function(a) {
                b.m(a, function(c) {
                    var f = c[0],
                        e = c[1],
                        d = f + "," + e,
                        a = h;
                    if (e || f) a = b.eb(h);
                    b.P(a, v[d]);
                    b.Hb(a, "hidden");
                    b.H(a, "absolute");
                    B.of(a);
                    n[d] = a;
                    b.J(a, !k)
                })
            })
        }

        function w() {
            var b = this,
                c = 0;
            m.call(b, 0, v);
            b.Ob = function(d, b) {
                if (b - c > h) {
                    c = b;
                    a && a.Yb(b);
                    g && g.Yb(b)
                }
            };
            b.vd = r
        }
        d.qf = function() {
            var a = 0,
                b = u.Kb,
                d = b.length;
            if (x) a = y++ % d;
            else a = c.floor(c.random() * d);
            b[a] && (b[a].xb = a);
            return b[a]
        };
        d.zf = function(w, x, l, m, b) {
            r = b;
            b = i(b, h);
            var j = m.Gc,
                f = l.Gc;
            j["no-image"] = !m.pc;
            f["no-image"] = !l.pc;
            var n = j,
                o = f,
                u = b,
                e = b.p || i({}, h);
            if (!b.bc) {
                n = f;
                o = j
            }
            var t = e.M || 0;
            g = new p(k, o, e, c.max(t - e.hb, 0), s, q);
            a = new p(k, n, u, c.max(e.hb - t, 0), s, q);
            g.Yb(0);
            a.Yb(0);
            v = c.max(g.Nd, a.Nd);
            d.xb = w
        };
        d.zb = function() {
            k.zb();
            g = j;
            a = j
        };
        d.Gf = function() {
            var b = j;
            if (a) b = new w;
            return b
        };
        if (b.tb() || b.Vc() || z && b.Je() < 537) h = 16;
        n.call(d);
        m.call(d, -1e7, 1e7)
    },
    i = function(o, fc) {
        var d = this;

        function Bc() {
            var a = this;
            m.call(a, -1e8, 2e8);
            a.Ff = function() {
                var b = a.Nb(),
                    d = c.floor(b),
                    f = t(d),
                    e = b - c.floor(b);
                return {
                    xb: f,
                    Bf: d,
                    Eb: e
                }
            };
            a.Ob = function(b, a) {
                var f = c.floor(a);
                if (f != a && a > b) f++;
                Tb(f, e);
                d.r(i.Df, t(a), t(b), a, b)
            }
        }

        function Ac() {
            var a = this;
            m.call(a, 0, 0, {
                sd: r
            });
            b.m(C, function(b) {
                D & 1 && b.fe(r);
                a.rc(b);
                b.M(kb / bc)
            })
        }

        function zc() {
            var a = this,
                b = Ub.kb;
            m.call(a, -1, 2, {
                e: f.Jc,
                de: {
                    Eb: Zb
                },
                sd: r
            }, b, {
                Eb: 1
            }, {
                Eb: -2
            });
            a.oc = b
        }

        function mc(o, n) {
            var b = this,
                f, g, h, k, c;
            m.call(b, -1e8, 2e8, {
                ed: 100
            });
            b.id = function() {
                M = e;
                R = j;
                d.r(i.jf, t(w.ib()), w.ib())
            };
            b.jd = function() {
                M = l;
                k = l;
                var a = w.Ff();
                d.r(i.Fe, t(w.ib()), w.ib());
                !a.Eb && Dc(a.Bf, s)
            };
            b.Ob = function(i, e) {
                var b;
                if (k) b = c;
                else {
                    b = g;
                    if (h) {
                        var d = e / h;
                        b = a.Ge(d) * (g - f) + f
                    }
                }
                w.lb(b)
            };
            b.Tb = function(a, d, c, e) {
                f = a;
                g = d;
                h = c;
                w.lb(a);
                b.lb(0);
                b.ld(c, e)
            };
            b.Ie = function(a) {
                k = e;
                c = a;
                b.kd(a, j, e)
            };
            b.Ke = function(a) {
                c = a
            };
            w = new Bc;
            w.qd(o);
            w.qd(n)
        }

        function oc() {
            var c = this,
                a = Xb();
            b.Q(a, 0);
            b.jb(a, "pointerEvents", "none");
            c.kb = a;
            c.of = function(c) {
                b.O(a, c);
                b.J(a)
            };
            c.zb = function() {
                b.W(a);
                b.Ac(a)
            }
        }

        function xc(o, g) {
            var f = this,
                q, L, v, k, y = [],
                x, B, W, G, Q, F, h, w, p;
            m.call(f, -u, u + 1, {});

            function E(a) {
                q && q.Bd();
                T(o, a, 0);
                F = e;
                q = new I.X(o, I, b.ce(b.s(o, "idle")) || lc);
                q.lb(0)
            }

            function Z() {
                q.qc < I.qc && E()
            }

            function M(p, r, o) {
                if (!G) {
                    G = e;
                    if (k && o) {
                        var h = o.width,
                            c = o.height,
                            n = h,
                            m = c;
                        if (h && c && a.rb) {
                            if (a.rb & 3 && (!(a.rb & 4) || h > K || c > J)) {
                                var j = l,
                                    q = K / J * c / h;
                                if (a.rb & 1) j = q > 1;
                                else if (a.rb & 2) j = q < 1;
                                n = j ? h * J / c : K;
                                m = j ? J : c * K / h
                            }
                            b.v(k, n);
                            b.A(k, m);
                            b.Z(k, (J - m) / 2);
                            b.Y(k, (K - n) / 2)
                        }
                        b.H(k, "absolute");
                        d.r(i.Oe, g)
                    }
                }
                b.W(r);
                p && p(f)
            }

            function Y(b, c, d, e) {
                if (e == R && s == g && N)
                    if (!Cc) {
                        var a = t(b);
                        A.zf(a, g, c, f, d);
                        c.Pe();
                        U.M(a - U.bd() - 1);
                        U.lb(a);
                        z.Tb(b, b, 0)
                    }
            }

            function bb(b) {
                if (b == R && s == g) {
                    if (!h) {
                        var a = j;
                        if (A)
                            if (A.xb == g) a = A.Gf();
                            else A.zb();
                        Z();
                        h = new vc(o, g, a, q);
                        h.Hd(p)
                    }!h.pd() && h.gc()
                }
            }

            function S(d, e, l) {
                if (d == g) {
                    if (d != e) C[e] && C[e].Qe();
                    else !l && h && h.Re();
                    p && p.Ic();
                    var m = R = b.mb();
                    f.Mb(b.T(j, bb, m))
                } else {
                    var k = c.min(g, d),
                        i = c.max(g, d),
                        o = c.min(i - k, k + r - i),
                        n = u + a.ff - 1;
                    (!Q || o <= n) && f.Mb()
                }
            }

            function db() {
                if (s == g && h) {
                    h.qb();
                    p && p.ef();
                    p && p.df();
                    h.Md()
                }
            }

            function eb() {
                s == g && h && h.qb()
            }

            function ab(a) {
                !P && d.r(i.cf, g, a)
            }

            function O() {
                p = w.pInstance;
                h && h.Hd(p)
            }
            f.Mb = function(c, a) {
                a = a || v;
                if (y.length && !G) {
                    b.J(a);
                    if (!W) {
                        W = e;
                        d.r(i.bf, g);
                        b.m(y, function(a) {
                            if (!b.L(a, "src")) {
                                a.src = b.s(a, "src2");
                                b.ab(a, a["display-origin"])
                            }
                        })
                    }
                    b.we(y, k, b.T(j, M, c, a))
                } else M(c, a)
            };
            f.gf = function() {
                var h = g;
                if (a.Od < 0) h -= r;
                var d = h + a.Od * tc;
                if (D & 2) d = t(d);
                if (!(D & 1) && !ib) d = c.max(0, c.min(d, r - u));
                if (d != g) {
                    if (A) {
                        var e = A.qf(r);
                        if (e) {
                            var i = R = b.mb(),
                                f = C[t(d)];
                            return f.Mb(b.T(j, Y, d, f, e, i), v)
                        }
                    }
                    cb(d)
                }
            };
            f.Bc = function() {
                S(g, g, e)
            };
            f.Qe = function() {
                p && p.ef();
                p && p.df();
                f.Pd();
                h && h.Ze();
                h = j;
                E()
            };
            f.Pe = function() {
                b.W(o)
            };
            f.Pd = function() {
                b.J(o)
            };
            f.Xe = function() {
                p && p.Ic()
            };

            function T(a, c, d) {
                if (b.L(a, "jssor-slider")) return;
                if (!F) {
                    if (a.tagName == "IMG") {
                        y.push(a);
                        if (!b.L(a, "src")) {
                            Q = e;
                            a["display-origin"] = b.ab(a);
                            b.W(a)
                        }
                    }
                    b.tb() && b.Q(a, (b.Q(a) || 0) + 1)
                }
                var f = b.Qb(a);
                b.m(f, function(f) {
                    var h = f.tagName,
                        i = b.s(f, "u");
                    if (i == "player" && !w) {
                        w = f;
                        if (w.pInstance) O();
                        else b.j(w, "dataavailable", O)
                    }
                    if (i == "caption") {
                        if (c) {
                            b.Uc(f, b.s(f, "to"));
                            b.Be(f, b.s(f, "bf"));
                            b.s(f, "3d") && b.Ye(f, "preserve-3d")
                        } else if (!b.Ed()) {
                            var g = b.eb(f, l, e);
                            b.Xb(g, f, a);
                            b.Rb(f, a);
                            f = g;
                            c = e
                        }
                    } else if (!F && !d && !k) {
                        if (h == "A") {
                            if (b.s(f, "u") == "image") k = b.If(f, "IMG");
                            else k = b.I(f, "image", e);
                            if (k) {
                                x = f;
                                b.ab(x, "block");
                                b.P(x, V);
                                B = b.eb(x, e);
                                b.H(x, "relative");
                                b.Fb(B, 0);
                                b.jb(B, "backgroundColor", "#000")
                            }
                        } else if (h == "IMG" && b.s(f, "u") == "image") k = f;
                        if (k) {
                            k.border = 0;
                            b.P(k, V)
                        }
                    }
                    T(f, c, d + 1)
                })
            }
            f.Ec = function(c, b) {
                var a = u - b;
                Zb(L, a)
            };
            f.xb = g;
            n.call(f);
            b.hf(o, b.s(o, "p"));
            b.lf(o, b.s(o, "po"));
            var H = b.I(o, "thumb", e);
            if (H) {
                b.eb(H);
                b.W(H)
            }
            b.J(o);
            v = b.eb(gb);
            b.Q(v, 1e3);
            b.j(o, "click", ab);
            E(e);
            f.pc = k;
            f.Ld = B;
            f.Gc = o;
            f.oc = L = o;
            b.O(L, v);
            d.Gb(203, S);
            d.Gb(28, eb);
            d.Gb(24, db)
        }

        function vc(y, g, p, q) {
            var a = this,
                n = 0,
                u = 0,
                h, j, f, c, k, t, r, o = C[g];
            m.call(a, 0, 0);

            function v() {
                b.Ac(L);
                cc && k && o.Ld && b.O(L, o.Ld);
                b.J(L, !k && o.pc)
            }

            function w() {
                a.gc()
            }

            function x(b) {
                r = b;
                a.qb();
                a.gc()
            }
            a.gc = function() {
                var b = a.Nb();
                if (!B && !M && !r && s == g) {
                    if (!b) {
                        if (h && !k) {
                            k = e;
                            a.Md(e);
                            d.r(i.We, g, n, u, h, c)
                        }
                        v()
                    }
                    var l, p = i.ud;
                    if (b != c)
                        if (b == f) l = c;
                        else if (b == j) l = f;
                    else if (!b) l = j;
                    else l = a.nd();
                    d.r(p, g, b, n, j, f, c);
                    var m = N && (!E || F);
                    if (b == c)(f != c && !(E & 12) || m) && o.gf();
                    else(m || b != f) && a.ld(l, w)
                }
            };
            a.Re = function() {
                f == c && f == a.Nb() && a.lb(j)
            };
            a.Ze = function() {
                A && A.xb == g && A.zb();
                var b = a.Nb();
                b < c && d.r(i.ud, g, -b - 1, n, j, f, c)
            };
            a.Md = function(a) {
                p && b.Hb(lb, a && p.vd.hd ? "" : "hidden")
            };
            a.Ec = function(b, a) {
                if (k && a >= h) {
                    k = l;
                    v();
                    o.Pd();
                    A.zb();
                    d.r(i.Ve, g, n, u, h, c)
                }
                d.r(i.Ue, g, a, n, j, f, c)
            };
            a.Hd = function(a) {
                if (a && !t) {
                    t = a;
                    a.Gb($JssorPlayer$.ee, x)
                }
            };
            p && a.rc(p);
            h = a.Cc();
            a.rc(q);
            j = h + q.Zc;
            f = h + q.ad;
            c = a.Cc()
        }

        function Kb(a, c, d) {
            b.Y(a, c);
            b.Z(a, d)
        }

        function Zb(c, b) {
            var a = x > 0 ? x : fb,
                d = zb * b * (a & 1),
                e = Ab * b * (a >> 1 & 1);
            Kb(c, d, e)
        }

        function Pb() {
            qb = M;
            Ib = z.nd();
            G = w.ib()
        }

        function gc() {
            Pb();
            if (B || !F && E & 12) {
                z.qb();
                d.r(i.Te)
            }
        }

        function ec(f) {
            if (!B && (F || !(E & 12)) && !z.pd()) {
                var d = w.ib(),
                    b = c.ceil(G);
                if (f && c.abs(H) >= a.cd) {
                    b = c.ceil(d);
                    b += jb
                }
                if (!(D & 1)) b = c.min(r - u, c.max(b, 0));
                var e = c.abs(b - d);
                e = 1 - c.pow(1 - e, 5);
                if (!P && qb) z.ge(Ib);
                else if (d == b) {
                    tb.Xe();
                    tb.Bc()
                } else z.Tb(d, b, e * Vb)
            }
        }

        function Hb(a) {
            !b.s(b.zc(a), "nodrag") && b.Pb(a)
        }

        function rc(a) {
            Yb(a, 1)
        }

        function Yb(a, c) {
            a = b.Xc(a);
            var k = b.zc(a);
            if (!O && !b.s(k, "nodrag") && sc() && (!c || a.touches.length == 1)) {
                B = e;
                yb = l;
                R = j;
                b.j(g, c ? "touchmove" : "mousemove", Bb);
                b.mb();
                P = 0;
                gc();
                if (!qb) x = 0;
                if (c) {
                    var h = a.touches[0];
                    ub = h.clientX;
                    vb = h.clientY
                } else {
                    var f = b.Nc(a);
                    ub = f.x;
                    vb = f.y
                }
                H = 0;
                hb = 0;
                jb = 0;
                d.r(i.Se, t(G), G, a)
            }
        }

        function Bb(d) {
            if (B) {
                d = b.Xc(d);
                var f;
                if (d.type != "mousemove") {
                    var l = d.touches[0];
                    f = {
                        x: l.clientX,
                        y: l.clientY
                    }
                } else f = b.Nc(d);
                if (f) {
                    var j = f.x - ub,
                        k = f.y - vb;
                    if (c.floor(G) != G) x = x || fb & O;
                    if ((j || k) && !x) {
                        if (O == 3)
                            if (c.abs(k) > c.abs(j)) x = 2;
                            else x = 1;
                        else x = O;
                        if (ob && x == 1 && c.abs(k) - c.abs(j) > 3) yb = e
                    }
                    if (x) {
                        var a = k,
                            i = Ab;
                        if (x == 1) {
                            a = j;
                            i = zb
                        }
                        if (!(D & 1)) {
                            if (a > 0) {
                                var g = i * s,
                                    h = a - g;
                                if (h > 0) a = g + c.sqrt(h) * 5
                            }
                            if (a < 0) {
                                var g = i * (r - u - s),
                                    h = -a - g;
                                if (h > 0) a = -g - c.sqrt(h) * 5
                            }
                        }
                        if (H - hb < -2) jb = 0;
                        else if (H - hb > 2) jb = -1;
                        hb = H;
                        H = a;
                        sb = G - H / i / (Y || 1);
                        if (H && x && !yb) {
                            b.Pb(d);
                            if (!M) z.Ie(sb);
                            else z.Ke(sb)
                        }
                    }
                }
            }
        }

        function bb() {
            qc();
            if (B) {
                B = l;
                b.mb();
                b.V(g, "mousemove", Bb);
                b.V(g, "touchmove", Bb);
                P = H;
                z.qb();
                var a = w.ib();
                d.r(i.Ee, t(a), a, t(G), G);
                E & 12 && Pb();
                ec(e)
            }
        }

        function jc(c) {
            if (P) {
                b.Ef(c);
                var a = b.zc(c);
                while (a && v !== a) {
                    a.tagName == "A" && b.Pb(c);
                    try {
                        a = a.parentNode
                    } catch (d) {
                        break
                    }
                }
            }
        }

        function Jb(a) {
            C[s];
            s = t(a);
            tb = C[s];
            Tb(a);
            return s
        }

        function Dc(a, b) {
            x = 0;
            Jb(a);
            d.r(i.Jf, t(a), b)
        }

        function Tb(a, c) {
            wb = a;
            b.m(S, function(b) {
                b.yc(t(a), a, c)
            })
        }

        function sc() {
            var b = i.fd || 0,
                a = X;
            if (ob) a & 1 && (a &= 1);
            i.fd |= a;
            return O = a & ~b
        }

        function qc() {
            if (O) {
                i.fd &= ~X;
                O = 0
            }
        }

        function Xb() {
            var a = b.Ib();
            b.P(a, V);
            b.H(a, "absolute");
            return a
        }

        function t(a) {
            return (a % r + r) % r
        }

        function kc(b, d) {
            if (d)
                if (!D) {
                    b = c.min(c.max(b + wb, 0), r - u);
                    d = l
                } else if (D & 2) {
                b = t(b + wb);
                d = l
            }
            cb(b, a.wc, d)
        }

        function xb() {
            b.m(S, function(a) {
                a.vc(a.Zb.Mf <= F)
            })
        }

        function hc() {
            if (!F) {
                F = 1;
                xb();
                if (!B) {
                    E & 12 && ec();
                    E & 3 && C[s].Bc()
                }
            }
        }

        function Ec() {
            if (F) {
                F = 0;
                xb();
                B || !(E & 12) || gc()
            }
        }

        function ic() {
            V = {
                cb: K,
                bb: J,
                g: 0,
                c: 0
            };
            b.m(T, function(a) {
                b.P(a, V);
                b.H(a, "absolute");
                b.Hb(a, "hidden");
                b.W(a)
            });
            b.P(gb, V)
        }

        function ab(b, a) {
            cb(b, a, e)
        }

        function cb(g, f, j) {
            if (Rb && (!B && (F || !(E & 12)) || a.td)) {
                M = e;
                B = l;
                z.qb();
                if (f == k) f = Vb;
                var d = Cb.Nb(),
                    b = g;
                if (j) {
                    b = d + g;
                    if (g > 0) b = c.ceil(b);
                    else b = c.floor(b)
                }
                if (D & 2) b = t(b);
                if (!(D & 1)) b = c.max(0, c.min(b, r - u));
                var i = (b - d) % r;
                b = d + i;
                var h = d == b ? 0 : f * c.abs(i);
                h = c.min(h, f * u * 1.5);
                z.Tb(d, b, h || 1)
            }
        }
        d.kd = function() {
            if (!N) {
                N = e;
                C[s] && C[s].Bc()
            }
        };

        function W() {
            return b.v(y || o)
        }

        function nb() {
            return b.A(y || o)
        }
        d.ob = W;
        d.sb = nb;

        function Eb(c, d) {
            if (c == k) return b.v(o);
            if (!y) {
                var a = b.Ib(g);
                b.Kc(a, b.Kc(o));
                b.Bb(a, b.Bb(o));
                b.ab(a, "block");
                b.H(a, "relative");
                b.Z(a, 0);
                b.Y(a, 0);
                b.Hb(a, "visible");
                y = b.Ib(g);
                b.H(y, "absolute");
                b.Z(y, 0);
                b.Y(y, 0);
                b.v(y, b.v(o));
                b.A(y, b.A(o));
                b.Uc(y, "0 0");
                b.O(y, a);
                var h = b.Qb(o);
                b.O(o, y);
                b.jb(o, "backgroundImage", "");
                b.m(h, function(c) {
                    b.O(b.s(c, "noscale") ? o : a, c);
                    b.s(c, "autocenter") && Lb.push(c)
                })
            }
            Y = c / (d ? b.A : b.v)(y);
            b.kf(y, Y);
            var f = d ? Y * W() : c,
                e = d ? c : Y * nb();
            b.v(o, f);
            b.A(o, e);
            b.m(Lb, function(a) {
                var c = b.me(b.s(a, "autocenter"));
                b.Yd(a, c)
            })
        }
        d.wf = Eb;
        n.call(d);
        d.kb = o = b.Jb(o);
        var a = b.N({
            rb: 0,
            ff: 1,
            lc: 1,
            kc: 0,
            jc: l,
            cc: 1,
            yb: e,
            td: e,
            Od: 1,
            Lc: 3e3,
            Hc: 1,
            wc: 500,
            Ge: f.pe,
            cd: 20,
            Mc: 0,
            q: 1,
            Oc: 0,
            nf: 1,
            ic: 1,
            yd: 1
        }, fc);
        a.yb = a.yb && b.Le();
        if (a.md != k) a.Lc = a.md;
        if (a.tf != k) a.Oc = a.tf;
        var fb = a.ic & 3,
            tc = (a.ic & 4) / -4 || 1,
            mb = a.af,
            I = b.N({
                X: q,
                yb: a.yb
            }, a.Rf);
        I.Kb = I.Kb || I.Nf;
        var Fb = a.ye,
            Z = a.Sd,
            eb = a.Of,
            Q = !a.nf,
            y, v = b.I(o, "slides", Q),
            gb = b.I(o, "loading", Q) || b.Ib(g),
            Nb = b.I(o, "navigator", Q),
            dc = b.I(o, "arrowleft", Q),
            ac = b.I(o, "arrowright", Q),
            Mb = b.I(o, "thumbnavigator", Q),
            pc = b.v(v),
            nc = b.A(v),
            V, T = [],
            uc = b.Qb(v);
        b.m(uc, function(a) {
            if (a.tagName == "DIV" && !b.s(a, "u")) T.push(a);
            else b.tb() && b.Q(a, (b.Q(a) || 0) + 1)
        });
        var s = -1,
            wb, tb, r = T.length,
            K = a.ae || pc,
            J = a.Wd || nc,
            Wb = a.Mc,
            zb = K + Wb,
            Ab = J + Wb,
            bc = fb & 1 ? zb : Ab,
            u = c.min(a.q, r),
            lb, x, O, yb, S = [],
            Qb, Sb, Ob, cc, Cc, N, E = a.Hc,
            lc = a.Lc,
            Vb = a.wc,
            rb, ib, kb, Rb = u < r,
            D = Rb ? a.cc : 0,
            X, P, F = 1,
            M, B, R, ub = 0,
            vb = 0,
            H, hb, jb, Cb, w, U, z, Ub = new oc,
            Y, Lb = [];
        if (r) {
            if (a.yb) Kb = function(a, c, d) {
                b.Ab(a, {
                    wb: c,
                    pb: d
                })
            };
            N = a.jc;
            d.Zb = fc;
            ic();
            b.L(o, "jssor-slider", e);
            b.Q(v, b.Q(v) || 0);
            b.H(v, "absolute");
            lb = b.eb(v, e);
            b.Xb(lb, v);
            if (mb) {
                cc = mb.Qf;
                rb = mb.X;
                ib = u == 1 && r > 1 && rb && (!b.Ed() || b.zd() >= 8)
            }
            kb = ib || u >= r || !(D & 1) ? 0 : a.Oc;
            X = (u > 1 || kb ? fb : -1) & a.yd;
            var Gb = v,
                C = [],
                A, L, Db = b.Ne(),
                ob = Db.Ae,
                G, qb, Ib, sb;
            Db.Id && b.jb(Gb, Db.Id, ([j, "pan-y", "pan-x", "none"])[X] || "");
            U = new zc;
            if (ib) A = new rb(Ub, K, J, mb, ob);
            b.O(lb, U.oc);
            b.Hb(v, "hidden");
            L = Xb();
            b.jb(L, "backgroundColor", "#000");
            b.Fb(L, 0);
            b.Xb(L, Gb.firstChild, Gb);
            for (var db = 0; db < T.length; db++) {
                var wc = T[db],
                    yc = new xc(wc, db);
                C.push(yc)
            }
            b.W(gb);
            Cb = new Ac;
            z = new mc(Cb, U);
            if (X) {
                b.j(v, "mousedown", Yb);
                b.j(v, "touchstart", rc);
                b.j(v, "dragstart", Hb);
                b.j(v, "selectstart", Hb);
                b.j(g, "mouseup", bb);
                b.j(g, "touchend", bb);
                b.j(g, "touchcancel", bb);
                b.j(h, "blur", bb)
            }
            E &= ob ? 10 : 5;
            if (Nb && Fb) {
                Qb = new Fb.X(Nb, Fb, W(), nb());
                S.push(Qb)
            }
            if (Z && dc && ac) {
                Z.cc = D;
                Z.q = u;
                Sb = new Z.X(dc, ac, Z, W(), nb());
                S.push(Sb)
            }
            if (Mb && eb) {
                eb.kc = a.kc;
                Ob = new eb.X(Mb, eb);
                S.push(Ob)
            }
            b.m(S, function(a) {
                a.sc(r, C, gb);
                a.Gb(p.Fc, kc)
            });
            b.jb(o, "visibility", "visible");
            Eb(W());
            b.j(v, "click", jc, e);
            b.j(o, "mouseout", b.Dc(hc, o));
            b.j(o, "mouseover", b.Dc(Ec, o));
            xb();
            a.lc && b.j(g, "keydown", function(b) {
                if (b.keyCode == 37) ab(-a.lc);
                else b.keyCode == 39 && ab(a.lc)
            });
            var pb = a.kc;
            if (!(D & 1)) pb = c.max(0, c.min(pb, r - u));
            z.Tb(pb, pb, 0)
        }
    };
i.cf = 21;
i.Se = 22;
i.Ee = 23;
i.jf = 24;
i.Fe = 25;
i.bf = 26;
i.Oe = 27;
i.Te = 28;
i.Df = 202;
i.Jf = 203;
i.We = 206;
i.Ve = 207;
i.Ue = 208;
i.ud = 209;
var p = {
        Fc: 1
    },
    r = function(d, C) {
        var f = this;
        n.call(f);
        d = b.Jb(d);
        var s, A, z, r, k = 0,
            a, m, i, w, x, h, g, q, o, B = [],
            y = [];

        function v(a) {
            a != -1 && y[a].ue(a == k)
        }

        function t(a) {
            f.r(p.Fc, a * m)
        }
        f.kb = d;
        f.yc = function(a) {
            if (a != r) {
                var d = k,
                    b = c.floor(a / m);
                k = b;
                r = a;
                v(d);
                v(b)
            }
        };
        f.vc = function(a) {
            b.J(d, a)
        };
        var u;
        f.sc = function(D) {
            if (!u) {
                s = c.ceil(D / m);
                k = 0;
                var p = q + w,
                    r = o + x,
                    n = c.ceil(s / i) - 1;
                A = q + p * (!h ? n : i - 1);
                z = o + r * (h ? n : i - 1);
                b.v(d, A);
                b.A(d, z);
                for (var f = 0; f < s; f++) {
                    var C = b.mf();
                    b.Qc(C, f + 1);
                    var l = b.ve(g, "numbertemplate", C, e);
                    b.H(l, "absolute");
                    var v = f % (n + 1);
                    b.Y(l, !h ? p * v : f % i * p);
                    b.Z(l, h ? r * v : c.floor(f / (n + 1)) * r);
                    b.O(d, l);
                    B[f] = l;
                    a.hc & 1 && b.j(l, "click", b.T(j, t, f));
                    a.hc & 2 && b.j(l, "mouseover", b.Dc(b.T(j, t, f), l));
                    y[f] = b.xc(l)
                }
                u = e
            }
        };
        f.Zb = a = b.N({
            Qd: 10,
            wd: 10,
            Yc: 1,
            hc: 1
        }, C);
        g = b.I(d, "prototype");
        q = b.v(g);
        o = b.A(g);
        b.Rb(g, d);
        m = a.dd || 1;
        i = a.B || 1;
        w = a.Qd;
        x = a.wd;
        h = a.Yc - 1;
        a.fc == l && b.L(d, "noscale", e);
        a.Lb && b.L(d, "autocenter", a.Lb)
    },
    t = function(a, g, h) {
        var c = this;
        n.call(c);
        var r, q, d, f, i;
        b.v(a);
        b.A(a);

        function k(a) {
            c.r(p.Fc, a, e)
        }

        function o(c) {
            b.J(a, c || !h.cc && d == 0);
            b.J(g, c || !h.cc && d >= q - h.q);
            r = c
        }
        c.yc = function(b, a, c) {
            if (c) d = a;
            else {
                d = b;
                o(r)
            }
        };
        c.vc = o;
        var m;
        c.sc = function(c) {
            q = c;
            d = 0;
            if (!m) {
                b.j(a, "click", b.T(j, k, -i));
                b.j(g, "click", b.T(j, k, i));
                b.xc(a);
                b.xc(g);
                m = e
            }
        };
        c.Zb = f = b.N({
            dd: 1
        }, h);
        i = f.dd;
        if (f.fc == l) {
            b.L(a, "noscale", e);
            b.L(g, "noscale", e)
        }
        if (f.Lb) {
            b.L(a, "autocenter", f.Lb);
            b.L(g, "autocenter", f.Lb)
        }
    };

function q(e, d, c) {
    var a = this;
    m.call(a, 0, c);
    a.Bd = b.Ad;
    a.Zc = 0;
    a.ad = c
}
jssor_1_slider_init = function() {
var g = [{
        i: 1200,
        n: 11,
        f: -1,
        e: {
            n: d.o,
            a: d.l,
            f: d.o
        },
        a: 2,
        S: {
            f: .5
        },
        p: {
            i: 1200,
            n: 1,
            f: 1,
            e: d.De,
            a: 2,
            S: {
                f: .5
            },
            M: 90
        }
    }, {
        i: 1400,
        x: .25,
        n: 1.5,
        e: {
            c: d.gd,
            n: d.rd
        },
        a: 2,
        u: -10,
        p: {
            i: 1400,
            x: -.25,
            n: 1.5,
            e: {
                c: d.gd,
                n: d.rd
            },
            a: 2,
            u: -10
        }
    }, {
        i: 1200,
        n: 11,
        f: 1,
        e: {
            a: d.l,
            f: d.o
        },
        a: 2,
        S: {
            f: 1
        },
        u: -10,
        p: {
            i: 1200,
            n: 11,
            f: -1,
            e: {
                a: d.l,
                f: d.o
            },
            a: 2,
            S: {
                f: 1
            },
            u: -10,
            M: 600
        }
    }, {
        i: 1500,
        x: .5,
        q: 2,
        R: {
            Ub: 3
        },
        e: {
            c: d.Af
        },
        a: 2,
        p: {
            i: 1500,
            a: 2
        }
    }, {
        i: 1500,
        x: -.3,
        y: .5,
        n: 1,
        f: .1,
        nb: {
            c: [.6, .4],
            g: [.6, .4],
            f: [.6, .4],
            n: [.6, .4]
        },
        e: {
            c: d.o,
            g: d.o,
            a: d.l,
            f: d.o
        },
        a: 2,
        p: {
            i: 1e3,
            n: 11,
            f: -.5,
            e: {
                a: d.l,
                f: d.o
            },
            a: 2,
            M: 200
        }
    }, {
        i: 1500,
        n: 11,
        f: .5,
        nb: {
            c: [.4, .6],
            g: [.4, .6],
            f: [.4, .6],
            n: [.4, .6]
        },
        e: {
            a: d.l,
            f: d.o
        },
        a: 2,
        p: {
            i: 1e3,
            n: 1,
            f: -.5,
            e: {
                a: d.l,
                f: d.o
            },
            a: 2,
            M: 200
        }
    }, {
        i: 1500,
        x: .3,
        nb: {
            c: [.6, .4]
        },
        e: {
            c: d.o,
            a: d.l
        },
        a: 2,
        hd: e,
        p: {
            i: 1e3,
            x: -.3,
            e: {
                c: d.o,
                a: d.l
            },
            a: 2
        }
    }, {
        i: 1200,
        x: .25,
        y: .5,
        f: -.1,
        e: {
            c: d.o,
            g: d.o,
            a: d.l,
            f: d.o
        },
        a: 2,
        p: {
            i: 1200,
            x: -.1,
            y: -.7,
            f: .1,
            e: {
                c: d.o,
                g: d.o,
                a: d.l,
                f: d.o
            },
            a: 2
        }
    }, {
        i: 1600,
        x: 1,
        B: 2,
        R: {
            Cb: 3
        },
        e: {
            c: d.z,
            a: d.l
        },
        a: 2,
        p: {
            i: 1600,
            x: -1,
            B: 2,
            R: {
                Cb: 3
            },
            e: {
                c: d.z,
                a: d.l
            },
            a: 2
        }
    }, {
        i: 1600,
        x: 1,
        B: 2,
        R: {
            Cb: 3
        },
        e: {
            c: d.z,
            a: d.l
        },
        a: 2,
        p: {
            i: 1600,
            x: -1,
            B: 2,
            R: {
                Cb: 3
            },
            e: {
                c: d.z,
                a: d.l
            },
            a: 2
        }
    }, {
        i: 1600,
        y: -1,
        q: 2,
        R: {
            Ub: 12
        },
        e: {
            g: d.z,
            a: d.l
        },
        a: 2,
        p: {
            i: 1600,
            y: 1,
            q: 2,
            R: {
                Ub: 12
            },
            e: {
                g: d.z,
                a: d.l
            },
            a: 2
        }
    }, {
        i: 1200,
        y: 1,
        e: {
            g: d.z,
            a: d.l
        },
        a: 2,
        p: {
            i: 1200,
            y: -1,
            e: {
                g: d.z,
                a: d.l
            },
            a: 2
        }
    }, {
        i: 1200,
        x: 1,
        e: {
            c: d.z,
            a: d.l
        },
        a: 2,
        p: {
            i: 1200,
            x: -1,
            e: {
                c: d.z,
                a: d.l
            },
            a: 2
        }
    }, {
        i: 1200,
        y: -1,
        e: {
            g: d.z,
            a: d.l
        },
        a: 2,
        u: -10,
        p: {
            i: 1200,
            y: -1,
            e: {
                g: d.z,
                a: d.l
            },
            a: 2,
            u: -10,
            M: -100
        }
    }, {
        i: 1200,
        x: 1,
        U: 40,
        q: 6,
        Db: o.dc,
        e: {
            c: d.z,
            a: d.l
        },
        a: 2,
        u: -10,
        p: {
            i: 1200,
            x: 1,
            U: 40,
            q: 6,
            Db: o.dc,
            e: {
                g: d.z,
                a: d.l
            },
            a: 2,
            u: -10,
            M: -100
        }
    }, {
        i: 1500,
        x: -.1,
        y: -.7,
        f: .1,
        nb: {
            c: [.6, .4],
            g: [.6, .4],
            f: [.6, .4]
        },
        e: {
            c: d.o,
            g: d.o,
            a: d.l,
            f: d.o
        },
        a: 2,
        p: {
            i: 1e3,
            x: .2,
            y: .5,
            f: -.1,
            e: {
                c: d.o,
                g: d.o,
                a: d.l,
                f: d.o
            },
            a: 2
        }
    }, {
        i: 1600,
        x: -.2,
        U: 40,
        q: 12,
        nb: {
            c: [.4, .6]
        },
        bc: e,
        Db: o.dc,
        tc: 260,
        e: {
            c: d.od,
            a: d.xd
        },
        a: 2,
        hd: e,
        S: {
            g: .5
        },
        p: {
            i: 1e3,
            x: .2,
            U: 40,
            q: 12,
            Db: o.dc,
            tc: 1028,
            e: {
                c: d.od,
                a: d.xd
            },
            a: 2,
            S: {
                g: .5
            }
        }
    }],
    j = {
        jc: e,
        md: 4e3,
        rb: 5,
        af: {
            X: s,
            Kb: g,
            xe: 1
        },
        Sd: {
            X: t
        },
        ye: {
            X: r
        }
    },
    f = new i("jssor_1", j);

function k() {
    var d = b.Hf(f.kb, "slides");
    if (d) {
        var c = d[1];
        if (c) {
            var a = b.I(c, "ad");
            if (!a) {
                a = b.Ib();
                //b.Bb(a, "position:absolute;top:0px;right:0px;width:80px;height:20px;background-color:rgba(255,255,140,0.5);font-size: 12px;line-height: 20px;text-align:center;");
                //b.Qc(a, "Jssor Slider");
                //b.O(c, a)
            }
        }
    }
}
k();

function a() {
    var b = f.kb.parentNode.clientWidth;
    if (b) {
        b = c.min(b, 600);
        //b = c.max(b, 210);
        f.wf(b)
    } else h.setTimeout(a, 30)
}
a();
b.j(h, "load", a);
b.j(h, "resize", a);
b.j(h, "orientationchange", a)
}
})(window, document, Math, null, true, false)