<%@ language = vbscript%>
<!-- #include file="..\Plugins\FPDF\fpdf.asp" --> 

<%
'paginas de ayuda del objeto FPDF
'FPDF.ORG
'https://web.archive.org/web/20100510144947/http://www.aspxnet.it/public/Default.asp?page=175&idp=21
'https://sites.google.com/site/aspfpdf/tutorials

'para añadir cabecera al pdf
function Header()
	'logo
	'pdf.Image "Logo_IMPRENTA.jpg",10,8,33,10, "","www.globaliaportal.com"
	'pdf.Image "Logo_IMPRENTA.jpg"
	'Arial bold 15
	pdf.SetFont "Arial","B",15
    'Movernos a la derecha
    pdf.Cell 80
    'Título
    pdf.Cell 30,10, "Title",1,0,"C"
    'Salto de línea
    pdf.Ln(20)
end function

'para añadir un Pie de página
function Footer()
    'Posición: a 1,5 cm del final
    pdf.SetY(-15)
    'Arial italic 8
    pdf.SetFont "Arial","I",8
    'Número de página
    pdf.Cell 0,10,"Page " & pdf.PageNo() & "/{nb}",0,0,"C"
end function

'creamos el pdf a adjuntar
Set pdf = CreateJsObject("FPDF")
pdf.CreatePDF()

pdf.SetPath("../Plugins/FPDF/FPDF/") 

'pdf.SetTitle "The title"
pdf.SetAuthor "Globalia Artes Gráficas"
'pdf.SetSubject "The subject"
'pdf.SetKeywords "The list of keywords"
pdf.SetCreator "Globalia Artes Gráficas"

pdf.SetFont "Arial","B",16
pdf.Open() 


pdf.AddPage()

'pdf.Image "Logo_GAG.jpg",10,10,40
pdf.Ln(20)

'pdf.Cell 40,10,"Hello, world!"
pdf.Cell 40,10, "¡Hola, Mundo!",1
pdf.Cell 60,10, "Hecho con FPDF.",0,1,"C"


pdf.SetFont "Times","U",18
pdf.SetTextColor 65,105,225
pdf.Write 9,"This is a link","http://www.google.com"


'ejemplo de tabla
pdf.AddPage()

'Colores, ancho de línea y fuente en negrita
pdf.SetFillColor 255,0,0
pdf.SetTextColor 255
pdf.SetDrawColor 128,0,0
pdf.SetLineWidth .3
'pdf.SetFont "","B"
pdf.SetFont "Arial","B",16

'Cabecera de la tabla
cabeceras = array("País", "Capital", "Superficie (km2)", "Pobl. (en miles)")
anchuras = array(40, 35, 45, 40)

anchototal=0

For Each x In anchuras
  anchototal= anchototal + x
Next

response.write("<br>ancho total: " & anchototal)


For x=0 to ubound(cabeceras)
	pdf.Cell anchuras(x),7,cabeceras(x),1,0,"C",true
next
pdf.Ln()

'Restauración de colores y fuentes
pdf.SetFillColor 224,235,255
pdf.SetTextColor 0
pdf.SetFont ""

'Datos
fill = false

for x=0 to 12
	pdf.Image "Logo_GAG.jpg", pdf.GetX(), pdf.GetY(), 30, 20
	pdf.Cell anchuras(0),20, "dato 1","LR",0,"L",fill
	pdf.Cell anchuras(1),20, "dato 2","LR",0,"L",fill
	pdf.Cell anchuras(2),20, "dato 3","LR",0,"R",fill
	pdf.Cell anchuras(3),20, "dato 4","LR",0,"R",fill
    pdf.Ln()
    fill = not fill
next

'Línea de cierre
pdf.Cell anchototal,0,"","T"


pdf.Close()
'pdf.Output
respuesta=pdf.Output("ejemplo.pdf", FALSE)

'response.write("<br><br>contenido pdf creado: " & repuesta)

response.write("<br><br>PDF CREADO")




   ' Primero, cree una instancia del objeto de servidor CDO
   Dim objCDO
   Set objCDO = Server.CreateObject("CDO.Message")

   ' Especifique la información del correo electrónico, incluyendo remitente, destinatario y cuerpo del mensaje
   objCDO.From     = "malba@globalia-artesgraficas.com"
   objCDO.To       = "malba@globalia-artesgraficas.com;manuel.alba.gallego@gmail.com"
   objCDO.Subject  = "Ejemplo de Envio de Correo con CDO y Adjunto un PDF con FPDF"
   'objCDO.TextBody = "cuerpo del mensaje."
   'objCDO.CreateMHTMLBody "http://www.w3schools.com/asp/" 
   
   strBody = "<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4.0 Transitional//EN"">" & vbCrLf _
	& "<html>" & vbCrLf _
	& "<head>" & vbCrLf _
	& " <title>Internal mailer example</title>" & vbCrLf _
	& " <meta http-equiv=Content-Type content=""text/html; charset=iso-8859-1"">" & vbCrLf _
	& "</head>" & vbCrLf _
	& "<body bgcolor=""#FFFFCC"">" & vbCrLf _
	& " <h2> This is what your internal mail will look like</h2>" & vbCrLf _
	& " <p>" & vbCrLf _
	& " This message was sent from a sample at" & vbCrLf _
	& " <a href=""http://www.hello-world.com"">hello world</a>." & vbCrLf _
	& " It is used to show people how to send HTML" & vbCrLf _
	& " formatted email if you want this kind of format rther than plain text" & vbCrLf _
	& " This is what your internal to external mail ," & vbCrLf _
	& "will look like, if you have any questions" & vbCrLf _
	& " get in touch with us at blah balh balh." & vbCrLf _
	& " <strong>" & vbCrLf _
	& "mesage generated by the MSMQ and our business recoreds." & vbCrLf _
	& " </strong>" & vbCrLf _
	& " </p>" & vbCrLf _
	& " <font size=""-1"">" & vbCrLf _
	& " <p>Please address all concerns to hello wrold@everywhere.com.</p>" & vbCrLf _
	& " <p>This message was sent to: " & strMailer & "</p>" & vbCrLf _
	& " </font>" & vbCrLf _
	& "</body>" & vbCrLf _
	& "</html>" & vbCrLf
   
	objCDO.HtmlBody = strBody

   'configuracion del servidor de emails
   objCDO.Configuration.Fields.Item("http://schemas.microsoft.com/cdo/configuration/sendusing") = 2
   objCDO.Configuration.Fields.Item("http://schemas.microsoft.com/cdo/configuration/smtpserver") = "192.168.150.44"
   'objMsg.Configuration.Fields.Item("http://schemas.microsoft.com/cdo/configuration/smtpserverport") = 25
   objCDO.Configuration.Fields.Update

   	' Especifique la ruta y el nombre del archivo que se desea adjuntar
	ruta=Request.ServerVariables("PATH_TRANSLATED")
	posicion=InStrRev(ruta,"\")
	'response.write("<br>ruta: " & ruta)
	'response.write("<br>posicion: " & posicion)
	ruta=left(ruta,posicion)
	ruta=ruta & "ejemplo.pdf"
	response.write("<br>adjunto: " & ruta)

   'objCDO.AddAttachment "D:\Intranets\Ventas\asp\adjunto.txt"
   objCDO.AddAttachment ruta
   'objCDO.AddAttachment(canvas)

   ' Use el método Send del objeto CDO para enviar el correo electrónico con el adjunto
   ''''objCDO.Send
%>
