<%
'ahora ya generamos el pdf a mostrar
Set Pdf = Server.CreateObject("Persits.Pdf")

' Open blank PDF form from file
plantilla_a_cargar="Plantilla_Ficha.pdf"
Set Doc = Pdf.OpenDocument(Server.MapPath(plantilla_a_cargar))

'Set Font = Doc.Fonts("Times-Roman")
'Set Font = Doc.Fonts("Symbol")
'Set Font = Doc.Fonts("Times-Bold")
'Set Font = Doc.Fonts("Times-Italic")
'Set Font = Doc.Fonts("Times-BoldItalic")---
'Set Font = Doc.Fonts("Helvetica")
Set Font = Doc.Fonts("Helvetica-Bold")
'Set Font = Doc.Fonts("Helvetica-Oblique")
'Set Font = Doc.Fonts("Helvetica-BoldOblique")
'Set Font = Doc.Fonts("Courier")-----
'Set Font = Doc.Fonts("Courier-Bold")
'Set Font = Doc.Fonts("Courier-Oblique")
'Set Font = Doc.Fonts("Courier-BoldOblique") 
'Set Font = Doc.Fonts("ZapfDingbats")

' Obtain the only page's canvas
Set Canvas = Doc.Pages(1).Canvas



'Set Image = Doc.OpenImage( Server.MapPath( "imagenes/logo_halcon.jpg") )
'Params = "x=140; y=723; scalex=1; scaley=1"
'Canvas.DrawImage Image, Params

Params = "x=130; y=727; width=612; alignment=left; size=6"
Canvas.DrawText "probando", Params, Font

Params = "x=130; y=710; width=612; alignment=left; size=6"
Canvas.DrawText "PRUEBA", Params, Font

str = "<HTML><TABLE><TR><TD>Text1</TD><TD>Text2</TD></TR></TABLE></HTML>"
Doc.ImportFromUrl str

' Save to HTTP stream
'asi saca directamente la ventana de ver o guardar el pdf
'Doc.SaveHttp "attachment;filename=hello.pdf"
	
'asi se muestra el pdf
'Doc.SaveHttp "filename=hello.pdf"
	
' Save document, the Save method returns generated file name
Filename = Doc.Save( Server.MapPath("Plantilla_Ficha2.pdf"), False )

Response.Write "Success! Download your PDF file <A HREF=" & Filename & ">here</A>"






   ' Primero, cree una instancia del objeto de servidor CDO
   Dim objCDO
   Set objCDO = Server.CreateObject("CDO.Message")

   ' Especifique la información del correo electrónico, incluyendo remitente, destinatario y cuerpo del mensaje
   objCDO.From     = "malba@globalia-artesgraficas.com"
   objCDO.To       = "malba@globalia-artesgraficas.com;manuel.alba.gallego@gmail.com"
   objCDO.Subject  = "Ejemplo de Envio de Correo con CDO"
   'objCDO.TextBody = "cuerpo del mensaje."
   'objCDO.CreateMHTMLBody "http://www.w3schools.com/asp/" 
   
   strBody = "<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4.0 Transitional//EN"">" & vbCrLf _
	& "<html>" & vbCrLf _
	& "<head>" & vbCrLf _
	& " <title>Internal mailer example</title>" & vbCrLf _
	& " <meta http-equiv=Content-Type content=""text/html; charset=iso-8859-1"">" & vbCrLf _
	& "</head>" & vbCrLf _
	& "<body bgcolor=""#FFFFCC"">" & vbCrLf _
	& " <h2> This is what your internal mail will look like</h2>" & vbCrLf _
	& " <p>" & vbCrLf _
	& " This message was sent from a sample at" & vbCrLf _
	& " <a href=""http://www.hello-world.com"">hello world</a>." & vbCrLf _
	& " It is used to show people how to send HTML" & vbCrLf _
	& " formatted email if you want this kind of format rther than plain text" & vbCrLf _
	& " This is what your internal to external mail ," & vbCrLf _
	& "will look like, if you have any questions" & vbCrLf _
	& " get in touch with us at blah balh balh." & vbCrLf _
	& " <strong>" & vbCrLf _
	& "mesage generated by the MSMQ and our business recoreds." & vbCrLf _
	& " </strong>" & vbCrLf _
	& " </p>" & vbCrLf _
	& " <font size=""-1"">" & vbCrLf _
	& " <p>Please address all concerns to hello wrold@everywhere.com.</p>" & vbCrLf _
	& " <p>This message was sent to: " & strMailer & "</p>" & vbCrLf _
	& " </font>" & vbCrLf _
	& "</body>" & vbCrLf _
	& "</html>" & vbCrLf
   
	objCDO.HtmlBody = strBody

   'configuracion del servidor de emails
   objCDO.Configuration.Fields.Item("http://schemas.microsoft.com/cdo/configuration/sendusing") = 2
   objCDO.Configuration.Fields.Item("http://schemas.microsoft.com/cdo/configuration/smtpserver") = "192.168.150.44"
   'objMsg.Configuration.Fields.Item("http://schemas.microsoft.com/cdo/configuration/smtpserverport") = 25
   objCDO.Configuration.Fields.Update

   	' Especifique la ruta y el nombre del archivo que se desea adjuntar
	ruta=Request.ServerVariables("PATH_TRANSLATED")
	posicion=InStrRev(ruta,"\")
	'response.write("<br>ruta: " & ruta)
	'response.write("<br>posicion: " & posicion)
	ruta=left(ruta,posicion)
	ruta=ruta & "Plantilla_Ficha2.pdf"
	response.write("<br>adjunto: " & ruta)

   'objCDO.AddAttachment "D:\Intranets\Ventas\asp\adjunto.txt"
   objCDO.AddAttachment ruta
   'objCDO.AddAttachment(canvas)

   ' Use el método Send del objeto CDO para enviar el correo electrónico con el adjunto
   objCDO.Send
%>
