<%
'****************************
'LITERALES EN ESPAÑOL DE LA PAGINA CONSULTA_PEDIDOS_GAG_CENTRAL_ADMIN.ASP

consulta_pedidos_gag_central_admin_title="Carrito Imprenta"

consulta_pedidos_gag_central_admin_panel_datos_pedido_articulos="Art&iacute;culos"
consulta_pedidos_gag_central_admin_panel_datos_pedido_articulos_alter="Consultar Art&iacute;culos"
consulta_pedidos_gag_central_admin_panel_datos_pedido_pedidos="Pedidos"
consulta_pedidos_gag_central_admin_panel_datos_pedido_pedidos_alter="Consultar Pedidos"

consulta_pedidos_gag_central_admin_panel_lista_pedidos_cabecera="Pedidos Realizados Por"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_cliente_alter="Cliente"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_cliente="Cliente"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_seleccionar_cliente="Seleccionar Cliente"

consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_num_pedido="N&uacute;m. Ped."
consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_num_pedido_alter="N&uacute;mero de Pedido"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_estado="Estado"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_estado_combo_seleccionar="Seleccionar Estado"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_fecha_inicio="Fec. Ini."
consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_fecha_inicio_alter="Fecha de Inicio"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_fecha_inicio_calendar_alter="Pulsa Aqu&iacute; Para Seleccionar Una Fecha de Inicio"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_fecha_fin="Fec. Fin"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_fecha_fin_alter="Fecha Fin"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_fecha_fin_calendar_alter="Pulsa Aqu&iacute; Para Seleccionar Una Fecha de Fin"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_tipos_oficina="Tipo Oficina"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_tipos_oficina_combo="-- TODOS --"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_boton_buscar="Buscar"

consulta_pedidos_gag_central_admin_panel_lista_pedidos_img_ascender="Ascender en La Lista de Pedidos"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_img_descender="Descender en La Lista de Pedidos"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_cabecera_columna_cliente="Cliente"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_cabecera_columna_num_pedido="N&uacute;m. Pedido"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_cabecera_columna_num_pedido_alter="N&uacute;mero de Pedido"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_cabecera_columna_fecha="Fecha"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_cabecera_columna_estado="Estado"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_cabecera_columna_accion="Acciones"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_no_hay_pedidos="A&uacute;n No Se Han Realizado Pedidos..."
consulta_pedidos_gag_central_admin_panel_lista_pedidos_boton_confirmar_alter="Confirmar Pedido"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_boton_cancelar_alter="Cancelar Pedido"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_boton_modificar_alter="Modificar Pedido"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_boton_descancelar_alter="Activar Pedido"

consulta_pedidos_gag_central_admin_pantalla_avisos_cabecera="Avisos"
consulta_pedidos_gag_central_admin_pantalla_avisos_boton_cerrar="Cerrar"




%>

