 
<%@ language=vbscript %>
<!--#include file="../../../../Data/Conexiones/Conexion_Gldistri.inc"-->
<%
		
	
	'recordsets
	dim sucursales
	
	
	dim codigosucursal
	dim nombresucursal

	'response.write(" hola ")

	codigosucursal=Request.Form("txtsucursal")
	if codigosucursal="" then
		codigosucursal=Request.QueryString("codsucursal")
	end if

	codigofamilia=Request.QueryString("codfamilia")
	nombrefamilia=Request.QueryString("nomfamilia")

	codigo_empresa=Request.Form("ocultocodigo_empresa")
	logotipo_empresa=Request.Form("ocultologotipo_empresa")

	'response.write("familia " & codigofamilia)
	if codigofamilia="" then
		codigofamilia=0
	end if
	'response.write("familia despues " & codigofamilia)
	
	set sucursales=Server.CreateObject("ADODB.Recordset")	

		with sucursales
			.ActiveConnection=conndistribuidora
			.Source="Select sucursal from sucursales where codigo='" & codigosucursal & "'"
			
			.Source= .Source & " and Empresa =" & codigo_empresa
			.Open
		end with

	nombresucursal=sucursales("sucursal")
	
	'response.write("source: " & sucursales.source)
	'response.write(" nombre suc: " & nombresucursal)

	
	'*****************************
	'CAMBIO 2011-11-25
	'solo para travelplan
	' en travelplan han de pasar 15 dias entre pedido y pedido
	
	'******************************
	'CAMBIO 2013-06-05, ahora lo amplian a 21 dias entre pedido y pedido
	permitir_pedir=1
	if codigo_empresa=3 then
		set pedidos_existentes=Server.CreateObject("ADODB.Recordset")	

		with pedidos_existentes
			.ActiveConnection=conndistribuidora

			.Source="SELECT max(Cabeceras_Pedidos_Sucursales.FECHA) as fecha"
			.Source= .Source & " FROM Cabeceras_Pedidos_Sucursales INNER JOIN SUCURSALES"
			.Source= .Source & " ON Cabeceras_Pedidos_Sucursales.SUCURSAL = SUCURSALES.Cod"		
			.Source= .Source & " WHERE SUCURSALES.CODIGO = '" & codigosucursal & "'"
			.Source= .Source & " AND SUCURSALES.Empresa = " & codigo_empresa

			'response.write("<br><br>" & .source)
			.Open
		end with

		if not pedidos_existentes.eof then
			'response.write("<br>dia de hoy: " & date() & "<br>dia pedido: " & pedidos_existentes("fecha") & "<br>diferencia: " & datediff("d",pedidos_existentes("fecha"),date()))
			if datediff("d",pedidos_existentes("fecha"),date()) < 21 then
				permitir_pedir=0
				fecha_ultimo_pedido=pedidos_existentes("fecha")
				fecha_posible_siguiente=dateadd("d", 21, pedidos_existentes("fecha"))
			end if
		end if


	end if

	

	
	
%>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 09/04/2002 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title></title>
<meta name="Description" content="">
<meta name="Keywords" content="">
<meta name="Author" content="Manuel Jose">
<meta name="Generator" content="AceHTML 4 Freeware">
<script languaje="javascript">
function comprobar(permitir,fecha_pedido, fecha_posible)
{
	if (permitir==0)
		{
		alert('No se Pueden Realizar 2 Pedidos en Menos de 21 Dias\n\nSu último Pedido se realizó el dia ' + fecha_pedido + '\n\nEl próximo Pedido no podrá realizarlo hasta el día ' + fecha_posible + '\n\nSi tiene alguna duda, póngase en contacto con Globalia Distribuciones (923 20 40 28)')

		location.href='../Bottom.asp?empresa=3'
		}
}
</script>
</head>
<frameset onload="comprobar(<%=permitir_pedir%>,'<%=fecha_ultimo_pedido%>','<%=fecha_posible_siguiente%>')" cols="27%,*" framespacing="0" frameborder="no" border="1"> 
  <frame name="familias" src="ListaFamilias.asp?codsucursal=<%=codigosucursal%>&nomsucursal=<%=nombresucursal%>&logo=<%=logotipo_empresa%>&codigo_empresa=<%=codigo_empresa%>">
  <frame name="articulos" src="ListaArticulos.asp?codsucursal=<%=codigosucursal%>&nomsucursal=<%=nombresucursal%>&codfamilia=<%=codigofamilia%>&nomfamilia=<%=nombrefamilia%>&logo=<%=logotipo_empresa%>&codigo_empresa=<%=codigo_empresa%>">
  <noframes> 
  <body>
  </body>
</noframes> </frameset>

  <body>
  </body>



<%
	sucursales.close
	pedidos_existentes.close
	conndistribuidora.close
	
	set sucursales=Nothing
	set pedidos_existentes=Nothing
	set conndistribuidora=Nothing
%>
</html>
