<%
'****************************
'LITERALES EN INGLES DE LA PAGINA CONSULTA_PEDIDOS_GAG_CENTRAL_ADMIN.ASP

consulta_pedidos_gag_central_admin_title="Order Manager"

consulta_pedidos_gag_central_admin_panel_datos_pedido_articulos="Articles"
consulta_pedidos_gag_central_admin_panel_datos_pedido_articulos_alter="Search Articles"
consulta_pedidos_gag_central_admin_panel_datos_pedido_pedidos="Orders"
consulta_pedidos_gag_central_admin_panel_datos_pedido_pedidos_alter="Search Orders"

consulta_pedidos_gag_central_admin_panel_lista_pedidos_cabecera="Orders Requested by"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_cliente_alter="User/Client"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_cliente="User/Client"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_seleccionar_cliente="Select client"

consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_num_pedido="N. Ord."
consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_num_pedido_alter="Number Order"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_estado="Status"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_estado_combo_seleccionar="Select Status"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_fecha_inicio="Start Date"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_fecha_inicio_alter="Start Date"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_fecha_inicio_calendar_alter="Click here to select start date"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_fecha_fin="End Date"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_fecha_fin_alter="End Date"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_fecha_fin_calendar_alter="Click here to select end date"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_tipos_oficina="Client Type"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_filtro_tipos_oficina_combo="-- ALL --"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_boton_buscar="Search"

consulta_pedidos_gag_central_admin_panel_lista_pedidos_img_ascender="Ascend in The Order List"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_img_descender="Descend in the Order List"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_cabecera_columna_cliente="Client"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_cabecera_columna_num_pedido="Number Order"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_cabecera_columna_num_pedido_alter="Number Order"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_cabecera_columna_fecha="Date"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_cabecera_columna_estado="Status"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_cabecera_columna_accion="Actions"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_no_hay_pedidos="Requests have not yet been made .."
consulta_pedidos_gag_central_admin_panel_lista_pedidos_boton_confirmar_alter="Confirm Order"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_boton_cancelar_alter="Cancel Order"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_boton_modificar_alter="Edit Order"
consulta_pedidos_gag_central_admin_panel_lista_pedidos_boton_descancelar_alter="Activate Order"

consulta_pedidos_gag_central_admin_pantalla_avisos_cabecera="Notices"
consulta_pedidos_gag_central_admin_pantalla_avisos_boton_cerrar="Close"



%>