<%
'****************************
'LITERALES EN INGLES DE LA PAGINA PLANTILLA_PERSONALIZACION.ASP

plantilla_personalizacion_title="Personalization template"
plantilla_personalizacion_cantidad="Quantity"
plantilla_personalizacion_nombre="Name"
plantilla_personalizacion_apellidos="Surnames"
plantilla_personalizacion_cargo="Position"
plantilla_personalizacion_telefono="Telf."
plantilla_personalizacion_fax="Fax"
plantilla_personalizacion_movil="Movil"
plantilla_personalizacion_email="Email"
plantilla_personalizacion_web="Web"
plantilla_personalizacion_calle="Street"
plantilla_personalizacion_numero="Number"
plantilla_personalizacion_poblacion="Location"
plantilla_personalizacion_cp="CIP"
plantilla_personalizacion_provincia="Region"
plantilla_personalizacion_pais="Country"
plantilla_personalizacion_email_envio="Email Send Proof"
plantilla_personalizacion_telefono_2="Telf. 2"
plantilla_personalizacion_boton_eliminar="Delete"
plantilla_personalizacion_campos_obligatorios="Required Gaps"
plantilla_personalizacion_horario="Schedule"
plantilla_personalizacion_horario_lu_vi="Hours of Service From Mon. to Fri."
plantilla_personalizacion_horario_sabados="Hours of Service on Saturdays"
plantilla_personalizacion_fecha_desde="Date From"
plantilla_personalizacion_fecha_hasta="Date To"
plantilla_personalizacion_porcentaje="Percentage (%)"
plantilla_personalizacion_servicios="Services"
plantilla_personalizacion_observaciones="Observations"
plantilla_personalizacion_ciudad="City"
plantilla_personalizacion_razon_social="Business Name"
plantilla_personalizacion_departamento="Department"
plantilla_personalizacion_numero_agencia="Num. Agency"
plantilla_personalizacion_localidad="Town"
plantilla_personalizacion_cibal="CIBAL"

plantilla_personalizacion_boton_agragar="Add Template"
plantilla_personalizacion_boton_guardar="Save Template"
plantilla_personalizacion_boton_cerrar="Close Template"
plantilla_personalizacion_error_cantidad="You must enter a Quantity in Template XXX."
plantilla_personalizacion_error_cantidad_numerico="The Amount of Template XXX must be an Integer."
plantilla_personalizacion_error_nombre="You must enter a Name in Template XXX."
plantilla_personalizacion_error_apellidos="You must enter a surname in Template XXX."
plantilla_personalizacion_error_cargo="You must enter a appointment in Template XXX."
plantilla_personalizacion_error_telefono="You must enter a Telephone in Template XXX."
plantilla_personalizacion_error_movil="You must enter a Mobile Telephone in Template XXX."
plantilla_personalizacion_error_email="You must enter an email in Template XXX."
plantilla_personalizacion_error_email_formato="Template Email XXX is incorrect."
plantilla_personalizacion_error_razon_social="You must enter a Business Name in Template XXX."
plantilla_personalizacion_error_calle="You must enter a Street in Template XXX."
plantilla_personalizacion_error_numero_calle="You must enter a Street Number in Template XXX."
plantilla_personalizacion_error_poblacion="You must enter a Location in Template XXX."
plantilla_personalizacion_error_cp="You must enter a CIP in Template XXX."
plantilla_personalizacion_error_provincia="You must enter a Region in Template XXX."
plantilla_personalizacion_error_email_prueba="You must enter an email for proof in Template XXX."
plantilla_personalizacion_error_email_prueba_formato="Template Email for proof  XXX is incorrect."
plantilla_personalizacion_error_numero_agencia="You must enter a Agency Number in Template XXX."
plantilla_personalizacion_error_localidad="You must enter a Town in Template XXX."
plantilla_personalizacion_error_cibal="You must enter a CIBAL in Template XXX."

plantilla_personalizacion_error_total_cantidad="The Sum of Quantities is XXX which is different from YYY."

plantilla_personalizacion_error_telefono_otros="You must enter a telephone number in Template."
plantilla_personalizacion_error_email_prueba_otros="You must enter an email for proof in Template."
plantilla_personalizacion_error_email_prueba_formato_otros="Template Email for proof  is incorrect."
plantilla_personalizacion_error_email_formato_otros="Template Email is incorrect."
plantilla_personalizacion_error_calle_otros="You must enter a Street in Template."
plantilla_personalizacion_error_numero_calle_otros="You must enter a Street Number in Template."
plantilla_personalizacion_error_poblacion_otros="You must enter a Location in Template."
plantilla_personalizacion_error_cp_otros="You must enter a CIP in Template."
plantilla_personalizacion_error_provincia_otros="You must enter a Region in Template."
plantilla_personalizacion_error_pais_otros="You must enter a Country in Template."
plantilla_personalizacion_error_horario_otros="You must enter a Schedule in Template."
plantilla_personalizacion_error_departamento_otros="Yoy must enter a Department."
plantilla_personalizacion_error_caracteres_especiales="The Data Must Not Contain These special characters: + # % & \\ "" [ ] { }"

plantilla_personalizacion_error_explicacion="The following errors have been detected:"
plantilla_personalizacion_pantalla_avisos_cabecera="Notices"
plantilla_personalizacion_pantalla_avisos_boton_cerrar="Close"
plantilla_personalizacion_pantalla_avisos_mensaje="Properly Collected Item Data"
plantilla_personalizacion_plantilla_completada="Template to Customize Item<BR>HAS ALREADY COMPLETED."
plantilla_personalizacion_error_ajax="¡Please, update your browser!"



%>