<%
' http://msdn.microsoft.com/en-us/library/ms526318(v=exchg.10).aspx
' Its good practice to use the module constants defined in the
' type library for the names.  The full names are used here to
' indicate that this is what is going on

 Const cdoSendUsingMethod        = "http://schemas.microsoft.com/cdo/configuration/sendusing"
 Const cdoSendUsingPort          = 2
 Const cdoSMTPServer             = "http://schemas.microsoft.com/cdo/configuration/smtpserver"
 Const cdoSMTPServerPort         = "http://schemas.microsoft.com/cdo/configuration/smtpserverport"
 Const cdoSMTPConnectionTimeout  = "http://schemas.microsoft.com/cdo/configuration/smtpconnectiontimeout"
 Const cdoSMTPAuthenticate       = "http://schemas.microsoft.com/cdo/configuration/smtpauthenticate"
 Const cdoBasic                  = 1
 Const cdoSendUserName           = "http://schemas.microsoft.com/cdo/configuration/sendusername"
 Const cdoSendPassword           = "http://schemas.microsoft.com/cdo/configuration/sendpassword"
 'Use SSL for the connection (False or True)
 Const cdoSendTLS        = "http://schemas.microsoft.com/cdo/configuration/smtpusessl"

' create CDOSYS objects
Set myMail = CreateObject("CDO.Message")
Set Fields = myMail.Configuration.Fields

' Configuración SMTP
With Fields
    .Item(cdoSendUsingMethod)   = cdoSendUsingPort
    '.Item(cdoSMTPServer)        = "192.168.150.44"
    .Item(cdoSMTPServer)        = "email-smtp.eu-west-1.amazonaws.com"
    .Item(cdoSMTPServerPort)    = 465 ' puerto 25 o 587 o 465
    .Item(cdoSMTPConnectionTimeout)  = 180
    .Item(cdoSMTPAuthenticate)  = cdoBasic
    .Item(cdoSendUserName)      = "AKIAY7674MHZ2YVMG4FB"
    .Item(cdoSendPassword)      = "BMh0vesbacnJDQqRGaJMn3WwPPwzxgdMMpz7yfq4/Tlj"
    .Item(cdoSendTLS)           = True
    .Update
End With

' Configurar detalles del correo electrónico
myMail.Subject = "Prueba CDO desde GAG"
myMail.From = "malba@globalia-artesgraficas.com"
myMail.To = "malba@globalia-artesgraficas.com;manuel.alba.gallego@gmail.com"
'myMail.TextBody = "Estamos probando el envío desde ASP en el server de GAG usando email-smtp.eu-west-1.amazonaws.com."


strBody = "<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4.0 Transitional//EN"">" & vbCrLf _
	& "<html>" & vbCrLf _
	& "<head>" & vbCrLf _
	& " <title>Internal mailer example</title>" & vbCrLf _
	& " <meta http-equiv=Content-Type content=""text/html; charset=iso-8859-1"">" & vbCrLf _
	& "</head>" & vbCrLf _
	& "<body bgcolor=""#FFFFCC"">" & vbCrLf _
	& " <h2> This is what your internal mail will look like</h2>" & vbCrLf _
	& " <p>" & vbCrLf _
	& " This message was sent from a sample at" & vbCrLf _
	& " <a href=""http://www.hello-world.com"">hello world</a>." & vbCrLf _
	& " It is used to show people how to send HTML" & vbCrLf _
	& " formatted email if you want this kind of format rther than plain text" & vbCrLf _
	& " This is what your internal to external mail ," & vbCrLf _
	& "will look like, if you have any questions" & vbCrLf _
	& " get in touch with us at blah balh balh." & vbCrLf _
	& " <strong>" & vbCrLf _
	& "mesage generated by the MSMQ and our business recoreds." & vbCrLf _
	& " </strong>" & vbCrLf _
	& " </p>" & vbCrLf _
	& " <font size=""-1"">" & vbCrLf _
	& " <p>Please address all concerns to hello wrold@everywhere.com.</p>" & vbCrLf _
	& " <p>This message was sent to: " & strMailer & "</p>" & vbCrLf _
	& " </font>" & vbCrLf _
	& "</body>" & vbCrLf _
	& "</html>" & vbCrLf
   
	myMail.HtmlBody = strBody



' Especifique la ruta y el nombre del archivo que se desea adjuntar
	ruta=Request.ServerVariables("PATH_TRANSLATED")
	posicion=InStrRev(ruta,"\")
	'response.write("<br>ruta: " & ruta)
	'response.write("<br>posicion: " & posicion)
	ruta=left(ruta,posicion)
	ruta=ruta & "adjunto2.txt"
	response.write("<br><br>adjunto: " & ruta)

   'myMail.AddAttachment "D:\Intranets\Ventas\asp\adjunto.txt"
   myMail.AddAttachment ruta

' Enviar el correo electrónico
On Error Resume Next
myMail.Send

If Err.Number = 0 Then
    Response.Write("<br><br>Correo electrónico enviado con éxito.")
Else
    Response.Write("<br><br>Error al enviar el correo electrónico: <br><br>" & Err.Description)
End If

' Liberar el objeto CDO
Set myMail = Nothing
%>

