<%
   ' Primero, cree una instancia del objeto de servidor CDO
   Dim objCDO
   Set objCDO = Server.CreateObject("CDO.Message")

   ' Especifique la información del correo electrónico, incluyendo remitente, destinatario y cuerpo del mensaje
   objCDO.From     = "noreply@globalia-artesgraficas.com"
   objCDO.To       = "malba@globalia-artesgraficas.com;manuel.alba.gallego@gmail.com"
   objCDO.Subject  = "Ejemplo de Envio de Correo con CDO"
   'objCDO.TextBody = "cuerpo del mensaje."
   'objCDO.CreateMHTMLBody "http://www.w3schools.com/asp/" 
   
   strBody = "<!DOCTYPE HTML PUBLIC ""-//W3C//DTD HTML 4.0 Transitional//EN"">" & vbCrLf _
	& "<html>" & vbCrLf _
	& "<head>" & vbCrLf _
	& " <title>Internal mailer example</title>" & vbCrLf _
	& " <meta http-equiv=Content-Type content=""text/html; charset=iso-8859-1"">" & vbCrLf _
	& "</head>" & vbCrLf _
	& "<body bgcolor=""#FFFFCC"">" & vbCrLf _
	& " <h2> This is what your internal mail will look like</h2>" & vbCrLf _
	& " <p>" & vbCrLf _
	& " This message was sent from a sample at" & vbCrLf _
	& " <a href=""http://www.hello-world.com"">hello world</a>." & vbCrLf _
	& " It is used to show people how to send HTML" & vbCrLf _
	& " formatted email if you want this kind of format rther than plain text" & vbCrLf _
	& " This is what your internal to external mail ," & vbCrLf _
	& "will look like, if you have any questions" & vbCrLf _
	& " get in touch with us at blah balh balh." & vbCrLf _
	& " <strong>" & vbCrLf _
	& "mesage generated by the MSMQ and our business recoreds." & vbCrLf _
	& " </strong>" & vbCrLf _
	& " </p>" & vbCrLf _
	& " <font size=""-1"">" & vbCrLf _
	& " <p>Please address all concerns to hello wrold@everywhere.com.</p>" & vbCrLf _
	& " <p>This message was sent to: " & strMailer & "</p>" & vbCrLf _
	& " </font>" & vbCrLf _
	& "</body>" & vbCrLf _
	& "</html>" & vbCrLf
   
	objCDO.HtmlBody = strBody

   'configuracion del servidor de emails
   objCDO.Configuration.Fields.Item("http://schemas.microsoft.com/cdo/configuration/sendusing") = 2
   objCDO.Configuration.Fields.Item("http://schemas.microsoft.com/cdo/configuration/smtpserver") = "192.168.150.44"
   'objMsg.Configuration.Fields.Item("http://schemas.microsoft.com/cdo/configuration/smtpserverport") = 25
   objCDO.Configuration.Fields.Update

   	' Especifique la ruta y el nombre del archivo que se desea adjuntar
	ruta=Request.ServerVariables("PATH_TRANSLATED")
	posicion=InStrRev(ruta,"\")
	'response.write("<br>ruta: " & ruta)
	'response.write("<br>posicion: " & posicion)
	ruta=left(ruta,posicion)
	ruta=ruta & "adjunto2.txt"
	response.write("<br>adjunto: " & ruta)

   'objCDO.AddAttachment "D:\Intranets\Ventas\asp\adjunto.txt"
   objCDO.AddAttachment ruta

   ' Use el método Send del objeto CDO para enviar el correo electrónico con el adjunto
   objCDO.Send
%>
